SELECT 'P |01|SB1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(B1_FILIAL, ' '))+'|'+RTRIM(COALESCE(B1_COD, ' ')), ' '), '|') AS BK_ITEM,
       SB1.B1_COD AS COD_ITEM,
       SB1.B1_DESC AS DESC_ITEM,
       SB1.B1_POSIPI AS CLASSIFICACAO_FISCAL,
       <<CODE_INSTANCE>> AS INSTANCIA
FROM SB1010 SB1
WHERE SB1.D_E_L_E_T_ = ' '
UNION
SELECT 'P |01|SB1010||',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO'