SELECT 'P |1' AS BK_DOCTMS,
       '1' AS CODIGO_DOCTMS,
       'Ordem de Coleta' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |2' AS BK_DOCTMS,
       '2' AS CODIGO_DOCTMS,
       'CTRC' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |3' AS BK_DOCTMS,
       '3' AS CODIGO_DOCTMS,
       'AWB' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |4' AS BK_DOCTMS,
       '4' AS CODIGO_DOCTMS,
       'Docto.Bx.Estoque' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |5' AS BK_DOCTMS,
       '5' AS CODIGO_DOCTMS,
       'Nota Fiscal' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |6' AS BK_DOCTMS,
       '6' AS CODIGO_DOCTMS,
       'CTRC Devolucao' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |7' AS BK_DOCTMS,
       '7' AS CODIGO_DOCTMS,
       'CTRC Reentrega' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |8' AS BK_DOCTMS,
       '8' AS CODIGO_DOCTMS,
       'CTRC Complemento' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |9' AS BK_DOCTMS,
       '9' AS CODIGO_DOCTMS,
       'CTRC Retorno' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |A' AS BK_DOCTMS,
       'A' AS CODIGO_DOCTMS,
       'CTRC Cortesia' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |B' AS BK_DOCTMS,
       'B' AS CODIGO_DOCTMS,
       'ACT' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |C' AS BK_DOCTMS,
       'C' AS CODIGO_DOCTMS,
       'Documento de Apoio 2' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |D' AS BK_DOCTMS,
       'D' AS CODIGO_DOCTMS,
       'Nota Fiscal Reentrega' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |E' AS BK_DOCTMS,
       'E' AS CODIGO_DOCTMS,
       'CTRC Armazenagem' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |F' AS BK_DOCTMS,
       'F' AS CODIGO_DOCTMS,
       'Nota Fiscal Armazenagem' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |G' AS BK_DOCTMS,
       'G' AS CODIGO_DOCTMS,
       'Nota Fiscal Complemento' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |H' AS BK_DOCTMS,
       'H' AS CODIGO_DOCTMS,
       'Documento de Apoio 3' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |I' AS BK_DOCTMS,
       'I' AS CODIGO_DOCTMS,
       'Documento de Apoio 4' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |J' AS BK_DOCTMS,
       'J' AS CODIGO_DOCTMS,
       'CRT' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |K' AS BK_DOCTMS,
       'K' AS CODIGO_DOCTMS,
       'Carregamento em Partes' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |L' AS BK_DOCTMS,
       'L' AS CODIGO_DOCTMS,
       'CRT Complemento' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |M' AS BK_DOCTMS,
       'M' AS CODIGO_DOCTMS,
       'CTRC Anulacao' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |N' AS BK_DOCTMS,
       'N' AS CODIGO_DOCTMS,
       'Documento de Apoio 5' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |O' AS BK_DOCTMS,
       'O' AS CODIGO_DOCTMS,
       'Documento de Apoio 6' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P |P' AS BK_DOCTMS,
       'P' AS CODIGO_DOCTMS,
       'CTRC Substituicao' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA

SELECT 'P |CTE' AS BK_DOCTMS,
       'CTE' AS CODIGO_DOCTMS,
       'DOCUMENTO AVULSO' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
SELECT 'P |RPS' AS BK_DOCTMS,
       'RPS' AS CODIGO_DOCTMS,
       'RPS E PEDIDO DE VENDA' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
SELECT 'P |ND' AS BK_DOCTMS,
       'ND' AS CODIGO_DOCTMS,
       'NOTA DE DEBITO' AS DESCRICAO_DOCTMS, <<CODE_INSTANCE>> AS INSTANCIA
UNION
SELECT 'P ||',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO'