select
	ST9.T9_FILIAL as FILIAL,
	trim(ST9.T9_CODBEM) as T9_CODBEM,
	trim(ST9.T9_STATUS) as STATUS,
	trim(TQS.TQS_MEDIDA) as TQS_MEDIDA,
	ST9.T9_TIPMOD as MODELO,
	ST9.T9_DTCOMPR as DATA,
	
    trim(ST9.T9_ITEMCTA) as T9_ITEMCTA,
    trim(ST9.T9_CCUSTO) as T9_CCUSTO,

	ST9.T9_VALCPA as CUSTO_COMPRA,
	ST9.T9_CONTACU as CONT_ACUMULADO,
	
	(select top 1 TQX010.TQX_KMESPO from TQX010 where TQX010.D_E_L_E_T_ = '' and TQX010.TQX_MEDIDA = TQS.TQS_MEDIDA) as km_ESPERADO,
	case when year(ST9.T9_DTCOMPR) > 2020 then 0.0 else TQS.TQS_XVLR1 + TQS.TQS_XVLR2 + TQS.TQS_XVLR3 + TQS.TQS_XVLR4 + TQS.TQS_XVLR5 end as VLR_SERV_LEGADO,
	TQS.TQS_KMOR + TQS.TQS_KMR1 + TQS.TQS_KMR2 + TQS.TQS_KMR3 + TQS.TQS_KMR4 + TQS.TQS_KMR5 + TQS.TQS_KMR6 + TQS.TQS_KMR7 as TOTAL_VIDAS

from TQS010 TQS
	inner join ST9010 ST9
		on ST9.D_E_L_E_T_ = ''
		and ST9.T9_CODBEM = TQS.TQS_CODBEM
where
		TQS.D_E_L_E_T_ = ''
