select
	CALCULOHODO.TP_DTLEITU,
	trim(CALCULOHODO.TP_CODBEM) as TP_CODBEM,
	min(CALCULOHODO.DIFF) as DIFF_MIN

from
	(
		select
			STP.TP_DTLEITU,
			STP.TP_CODBEM,
			STP.TP_ACUMCON as HOD_ATU,
			CONTADOR.TP_ACUMCON as HOD_ANT,
			STP.TP_ACUMCON - CONTADOR.TP_ACUMCON as DIFF
		from STP010 as STP
			inner join
			(
				select
					STP010.TP_CODBEM,
					STP010.TP_ACUMCON,
					STP010.TP_DTLEITU
				from STP010
				where STP010.D_E_L_E_T_ = ''
			) as CONTADOR
				on CONTADOR.TP_CODBEM = STP.TP_CODBEM
				and CONTADOR.TP_DTLEITU < STP.TP_DTLEITU
	
			left join ST9010 as ST9
				on ST9.D_E_L_E_T_ = ''
				and ST9.T9_CODBEM = STP.TP_CODBEM
		where trim(STP.TP_CODBEM) like '[A-Z]%'
	) CALCULOHODO
where CALCULOHODO.DIFF >= 0
group by
	CALCULOHODO.TP_DTLEITU,
	CALCULOHODO.TP_CODBEM