select
	trim(TQZ.TQZ_CODBEM) as TQZ_CODBEM,
	trim(TQZ.TQZ_DTSTAT) as TQZ_DTSTAT,
	trim(TQZ.TQZ_HRSTAT) as TQZ_HRSTAT,
	trim(TQZ.TQZ_STATUS) as TQZ_STATUS,
	trim(TQZ.TQZ_PRODUT) as TQZ_PRODUT,
	trim(TQZ.TQZ_ALMOX) as TQZ_ALMOX,
	trim(TQZ.TQZ_NUMSEQ) as TQZ_NUMSEQ,
	trim(TQZ.TQZ_ORIGEM) as TQZ_ORIGEM
from TQZ010 TQZ
where TQZ.D_E_L_E_T_ = ''