select
	TQZ.TQZ_CODBEM,
	TQZ.TQZ_DTSTAT,
	TQZ.TQZ_HRSTAT,
	TQZ.TQZ_STATUS,
	TQZ.TQZ_PRODUT,
	TQZ.TQZ_ALMOX,
	TQZ.TQZ_NUMSEQ,
	TQZ.TQZ_ORIGEM
from TQZ010 TQZ
where
        TQZ.D_E_L_E_T_ = ''
    and year(TQZ.TQZ_DTSTAT) > 2022
