select
	trim(isnull(DESC_SERVICO.B1_DESC, '-')) as NOME_SERVICO,
	SERVICO.D1_COD,
	trim(isnull(SERVICO.D1_FILIAL, '-')) as SERV_FILIAL,
	trim(isnull(SERVICO.D1_DOC, '-')) as SERV_DOC,
	trim(isnull(SERVICO.D1_SERIE, '-')) as SERV_SERIE,
	trim(isnull(SERVICO.D1_ITEM, '-')) as SERV_ITEM,
	trim(isnull(SERVICO.D1_TES, '-')) as SERV_TES,
	trim(isnull(SERVICO.D1_EMISSAO, '-')) as SERV_DATA_ENTRADA,
	SERVICO.D1_QUANT as SERV_QUANT,
	SERVICO.D1_TOTAL as SERV_TOTAL,
	SERVICO.D1_CUSTO as SERV_CUSTO,
	SERVICO.D1_VALDESC as SERV_VALDESC,
	SERVICO.D1_LOCAL as SERV_LOCAL,
	SERVICO.D1_PEDIDO as SERV_PEDIDO,
	trim(isnull(SERVICO.D1_FORNECE, '-')) + '-' + trim(isnull(SERVICO.D1_LOJA, '-')) as FORNECEDOR_SERV,

	trim(isnull(RETORNO.D1_FILIAL, '-')) as D1_FILIAL,
	trim(isnull(RETORNO.D1_DOC, '-')) as D1_DOC,
	trim(isnull(RETORNO.D1_SERIE, '-')) as D1_SERIE,
	trim(isnull(RETORNO.D1_ITEM, '-')) as D1_ITEM,
	trim(isnull(RETORNO.D1_TES, '-')) as D1_TES,
	trim(isnull(RETORNO.D1_EMISSAO, '-')) as DATA_ENTRADA,
	RETORNO.D1_QUANT,
	RETORNO.D1_TOTAL,
	RETORNO.D1_CUSTO,
	RETORNO.D1_VALDESC,
	RETORNO.D1_LOCAL,

	trim(isnull(DESC_PECA.B1_DESC, '-')) as NOME_PECA,
	REMESSA.D2_COD,
	trim(isnull(REMESSA.D2_FILIAL, '-')) as D2_FILIAL,
	trim(isnull(REMESSA.D2_DOC, '-')) as D2_DOC,
	trim(isnull(REMESSA.D2_SERIE, '-')) as D2_SERIE,
	trim(isnull(REMESSA.D2_ITEM, '-')) as D2_ITEM,
	trim(isnull(REMESSA.D2_TES, '-')) as D2_TES,
	trim(isnull(REMESSA.D2_EMISSAO, '-')) as DATA_SAIDA,
	REMESSA.D2_QUANT,
	REMESSA.D2_TOTAL,
	REMESSA.D2_LOCAL,
	trim(isnull(REMESSA.D2_CLIENTE, '-')) + '-' + trim(isnull(REMESSA.D2_LOJA, '-')) as FORNECEDOR_PECA,

	year(RETORNO.D1_EMISSAO) as ANO_ENTRADA,
	month(RETORNO.D1_EMISSAO) as MES_ENTRADA,
	year(REMESSA.D2_EMISSAO) as ANO_SAIDA,
	month(REMESSA.D2_EMISSAO) as MES_SAIDA,
	year(SERVICO.D1_EMISSAO) as ANO_SERVICO,
	month(SERVICO.D1_EMISSAO) as MES_SERVICO
from SD1010 SERVICO (nolock)
	left join SD1010 RETORNO (nolock)
		on RETORNO.D_E_L_E_T_ = ''
		and RETORNO.D1_FILIAL = SERVICO.D1_FILIAL
		and RETORNO.D1_DOC = SERVICO.D1_NFORI
		and RETORNO.D1_SERIE = SERVICO.D1_SERIORI
		and RETORNO.D1_ITEM = SERVICO.D1_ITEMORI
		and RETORNO.D1_FORNECE = SERVICO.D1_FORNECE
		and RETORNO.D1_LOJA = SERVICO.D1_LOJA

		left join SD2010 REMESSA (nolock)
			on REMESSA.D_E_L_E_T_ = ''
			and REMESSA.D2_FILIAL = RETORNO.D1_FILIAL
			and REMESSA.D2_COD = RETORNO.D1_COD
			and REMESSA.D2_DOC = RETORNO.D1_NFORI
			and REMESSA.D2_SERIE = RETORNO.D1_SERIORI
			and REMESSA.D2_ITEM = RETORNO.D1_ITEMORI
			and REMESSA.D2_CLIENTE = RETORNO.D1_FORNECE
			and REMESSA.D2_LOJA = RETORNO.D1_LOJA

			inner join SB1010 DESC_PECA (nolock)
				on DESC_PECA.D_E_L_E_T_ = ''
				and DESC_PECA.B1_COD = REMESSA.D2_COD

	inner join SB1010 DESC_SERVICO (nolock)
		on DESC_SERVICO.D_E_L_E_T_ = ''
		and DESC_SERVICO.B1_COD = SERVICO.D1_COD
where SERVICO.D_E_L_E_T_ = ''