select
	CUBO.PARAMSFONTEDADOS,
	substring(CUBO.PARAMSFONTEDADOS, 5, len(CUBO.PARAMSFONTEDADOS)),
	SSQL.CODSENTENCA,
	CUBO.NOME,
	CUBO.DESCRICAO,
	CUBO.IDFONTEDADOS,
	CUBO.DIASATUALIZACAO,
	CUBO.RECcreatedON,
	CUBO.RECmodifiedON,
	SSQL.RECcreatedON,
	SSQL.RECmodifiedON
from GCONSSQL as SSQL (nolock)
	inner join QCUBOX as CUBO (nolock)
		on SSQL.CODCOLIGADA = CUBO.CODCOLIGADA
		and SSQL.CODSENTENCA = substring(CUBO.PARAMSFONTEDADOS, 5, len(CUBO.PARAMSFONTEDADOS))
where year(SSQL.RECmodifiedON) > 2020