SELECT ZG1_CODIGO,ZG1_VLTOTL FROM ZG1010 WHERE D_E_L_E_T_ = ' ' AND ZG1_TIPO = 'Despesa Contabil' AND ZG1_COMPET = '202303' AND ZG1_ATIVO = 'S'

SELECT SUM(VALOR),
       CODIGO
FROM
  (SELECT SUM(CT2_VALOR) AS VALOR,
          ZA8_COD AS CODIGO
   FROM CT2010 CT2
   JOIN ZA8010 ZA8 ON (CT2_DEBITO BETWEEN ZA8_CT1INI AND ZA8_CT1FIM
                       AND CT2_ITEMD BETWEEN ZA8_CTDINI AND ZA8_CTDFIM
                       AND CT2_CCD BETWEEN ZA8_CTTINI AND ZA8_CTTFIM
                       AND ZA8.D_E_L_E_T_ = '')
   WHERE CT2_DATA BETWEEN '20230301' AND '20230331'
     AND CT2.D_E_L_E_T_ = ''
   GROUP BY ZA8_COD
   UNION ALL SELECT SUM(CT2_VALOR) *-1 AS VALOR,
                    ZA8_COD AS CODIGO
   FROM CT2010 CT2
   JOIN ZA8010 ZA8 ON (CT2_CREDIT BETWEEN ZA8_CT1INI AND ZA8_CT1FIM
                       AND CT2_ITEMC BETWEEN ZA8_CTDINI AND ZA8_CTDFIM
                       AND CT2_CCC BETWEEN ZA8_CTTINI AND ZA8_CTTFIM
                       AND ZA8.D_E_L_E_T_ = '')
   WHERE CT2_DATA BETWEEN '20230301' AND '20230331'
     AND CT2.D_E_L_E_T_ = ''
   GROUP BY ZA8_COD)P
GROUP BY CODIGO

SELECT ZC2_COD,SUM(ZC2_TOTAL) FROM ZC2010 WHERE D_E_L_E_T_  = '' AND ZC2_TIPO ='7' AND SUBSTRING(ZC2_COMPET,1,6) = '202303' GROUP BY ZC2_COD ORDER BY ZC2_COD