// QUERY PRINCIPAL DO PROCESSO DA MANUTENÇÃO

SELECT TJ_CODBEM,
       T9_NOME,
       ZC2.ZC2_NUM,
       TJ_DTORIGI,
       ISNULL(ZC2.R_E_C_N_O_, 0) REGZC2,
       ZC2_QTDREA QUANT,
       VALOR/TOTQTD*ZC2.ZC2_QTDREA VLUREA,
       ZC2_TOTAL,
       T9_CODBEM,
       T6_YHRPADR,
       T9_YPORTAL
FROM
  (SELECT TJ_CODBEM,
          SUM((TJ_CUSTMDO+TJ_CUSTMAT+TJ_CUSTMAA+TJ_CUSTMAS)/CASE
                                                                WHEN TJ_YVLD>0 THEN TJ_YVLD
                                                                ELSE 1
                                                            END) VALOR,
          MAX(TJ_DTORIGI) TJ_DTORIGI
   FROM STJ010 STJ
   WHERE TJ_FILIAL='010102'
     AND TJ_DTORIGI BETWEEN '20230201' AND '20230228'
     AND TJ_DTORIGI BETWEEN CASE
                                WHEN TJ_YVLD>1 THEN CONVERT(VARCHAR(8), DATEADD(m, (TJ_YVLD-1)*-1, '20230201'), 112)
                                ELSE '20230201'
                            END AND '20230228'
     AND TJ_SITUACA='L'
     AND STJ.D_E_L_E_T_=' '
   GROUP BY TJ_CODBEM) TABSTJ
INNER JOIN ZC2010 ZC2 ON ZC2.ZC2_FILIAL='010102'
AND TJ_CODBEM=ZC2.ZC2_COD
AND ZC2.ZC2_TIPO='3'
AND ZC2.ZC2_DATA BETWEEN '20230201' AND '20230228'
AND ZC2.ZC2_COMPET='        '
AND ZC2.D_E_L_E_T_=' '
INNER JOIN
  (SELECT ZC2_COD TOTCOD,
          SUM(ZC2_QTDREA) TOTQTD
   FROM ZC2010 ZC2
   WHERE ZC2_FILIAL='010102'
     AND ZC2_DATA BETWEEN '20230201' AND '20230228'
     AND ZC2_TIPO='3'
     AND ZC2_COMPET='        '
     AND ZC2.D_E_L_E_T_=' '
   GROUP BY ZC2_COD) TOTZC2 ON TJ_CODBEM=TOTCOD
INNER JOIN ST9010 ST9 ON T9_CODBEM=TJ_CODBEM
AND ST9.D_E_L_E_T_<>'*'
INNER JOIN ST6010 ST6 ON T6_CODFAMI=T9_CODFAMI
AND ST6.D_E_L_E_T_<>'*'

// TABELA DE LOG 
SELECT * FROM ZG1010 WHERE ZG1_TIPO = 'Manutenção' AND ZG1_ATIVO = 'S' AND D_E_L_E_T_ = ' '

// SOMA DO CUSTO MESAL POR BEM
SELECT SUM(TL_CUSTO) AS CUSTOTOT
FROM STJ010 STJ
	INNER JOIN STL010 STL ON TL_ORDEM=TJ_ORDEM
	AND STL.D_E_L_E_T_<>'*'
WHERE STJ.D_E_L_E_T_<>'*'
  AND TJ_DTORIGI BETWEEN '20230201' AND '20230228'
  AND TJ_CODBEM = 'H01'
  AND TL_DOC <> ' '
  

// SOMA DAS HORAS DE APONTAMENTO DO BEM POR MES - HORAS PRODUTIVAS
SELECT SUM(datediff(MINUTE, concat(ZC2.ZC2_DTINI, ' ', ZC2.ZC2_HRINI), concat(ZC2.ZC2_DTFIM, ' ', ZC2.ZC2_HRFIM))/60.0) AS HrApont
FROM ZC2010 ZC2
WHERE ZC2_FILIAL='010102'
  AND ZC2_DATA BETWEEN '20230201' AND '20230228'
  AND ZC2_TIPO='3'
  AND ZC2.D_E_L_E_T_=' '
  AND (ZC2_DTINI <> ' '
       AND ZC2_DTFIM <> ' '
       AND ZC2_HRINI <> ' '
       AND ZC2_HRFIM <> ' ')
  AND ZC2_COD = 'H01'