SELECT
    SD2.D2_FILIAL as BK_FILIAL,
    SF2.F2_SERIE AS SERIE_DA_NOTA_FISCAL,
    SF2.F2_DOC AS NUMERO_DA_NOTA_FISCAL,
    SD2.D2_PEDIDO AS NUMERO_PEDIDO_VENDA,
    SD2.D2_ITEM AS NUMERO_ITEM,
    convert(date, SF2.F2_EMISSAO, 103) as DATA_DE_EMISSAO,
    convert(date, SF2.F2_EMINFE, 103) as DATA_SAIDA_NF,
    SF2.F2_TPFRETE AS TIPO_DE_FRETE,
    SD2.D2_TIPO AS TIPO_DE_NOTA_FISCAL,
    SD2.D2_ORIGLAN AS ORIGEM_DO_LANCAMENTO,

    trim(SF3.F3_DESCRET) as MSG_NFE,
    trim(SF3.F3_OBSERV) as OBS,
    convert(date, SF3.F3_DTCANC, 103) as DATA_CANCELAMENTO,
    
    trim(D2_COD) as BK_ITEM,
    trim(SB1.B1_DESC) as DESC_PRODUTO,
    
    trim(B1_GRUPO) as BK_GRUPO_DE_ESTOQUE_PRODUTO,
    trim(SBM.BM_DESC) as DESC_GRUPOPROD,
    
    trim(F2_VEND1) as BK_VENDEDOR,
    trim(SA3.A3_NOME) as VENDEDOR,
    
    trim(D2_TES) as BK_TES,
    trim(SF4.F4_TEXTO) as TES,
    
    trim(D2_CF) as BK_CFOP,
    trim(CFOP.X5_DESCRI) as CFOP,
    
    trim(A1_TIPO) as BK_GRUPO_DE_CLIENTE,
    trim(SA1.A1_TIPO) as TIPO_CLIENTE,
    
    trim(D2_CLIENTE) as BK_CLIENTE,
    trim(SA1.A1_NOME) as CLIENTE,

    CAST(COALESCE(D2_VALBRUT, 0) AS DECIMAL(14, 2)) AS VL_FATURAMENTO_TOTAL,
    CAST(COALESCE(D2_VALICM, 0) AS DECIMAL(14, 2)) AS VL_ICMS_FATURAMENTO,
    CAST(COALESCE(D2_VALIPI, 0) AS DECIMAL(14, 2)) AS VL_IPI_FATURAMENTO,
    CAST(COALESCE(D2_VALFRE, 0) AS DECIMAL(14, 2)) AS VL_FRETE_NF,
    CAST(COALESCE(D2_DESPESA, 0) AS DECIMAL(14, 2)) AS VL_DESPESA,
    CAST(COALESCE(D2_TOTAL, 0) AS DECIMAL(14, 2)) AS VL_FATURAMENTO_MERCADORIA,
    CAST(COALESCE(D2_VALIMP6, 0) AS DECIMAL(14, 2)) AS VL_PIS_FATURAMENTO,
    CAST(COALESCE(D2_VALIMP5, 0) AS DECIMAL(14, 2)) AS VL_COFINS_FATURAMENTO,
    CAST(COALESCE(D2_QUANT, 0) AS DECIMAL(13, 3)) AS QTD_FATURADA_ITEM,
    CAST(COALESCE(D2_VALISS, 0) AS DECIMAL(14, 2)) AS VL_ISS_FATURAMENTO,
    CAST(COALESCE(D2_ICMSRET, 0) AS DECIMAL(14, 2)) AS VL_ICMS_SUBST_FATURAMENTO,
    CAST(COALESCE(D2_DESCON, 0) AS DECIMAL(12, 2)) AS VL_DESCONTO_FATURAMENTO,
    CAST(COALESCE(D2_VALIRRF, 0) AS DECIMAL(14, 2)) AS VL_IRF_FATURAMENTO,
    CAST(COALESCE(D2_VALINS, 0) AS DECIMAL(14, 2)) AS VL_INSS_FATURAMENTO,
    CAST(COALESCE(D2_PESO * D2_QUANT, 0) AS DECIMAL(12, 4)) AS PESO_LIQUIDO,
    CAST(COALESCE(B1_PESBRU * D2_QUANT, 0) AS DECIMAL(12, 4)) AS PESO_BRUTO,
    1 AS QTD,
    CAST(COALESCE(D2_PRUNIT, 0) AS DECIMAL(16, 4)) AS VL_UNITARIO,
    CAST(COALESCE(D2_SEGURO, 0) AS DECIMAL(14, 2)) AS VL_SEGURO
FROM SF3010
    inner join SF2010 SF2
        on SF3.D_E_L_E_T_ = ''
        and SF3.F3_CLIEFOR = SF2.F2_CLIENTE
        and SF3.F3_LOJA = SF2.F2_LOJA
        and SF3.F3_NFISCAL = SF2.F2_DOC
        and SF3.F3_SERIE = SF2.F2_SERIE

        left JOIN SD2010 SD2
            on SD2.D_E_L_E_T_= ' '
            and SD2.D2_FILIAL = SF2.F2_FILIAL
            and SD2.D2_CLIENTE = SF2.F2_CLIENTE
            and SD2.D2_LOJA = SF2.F2_LOJA
            and SD2.D2_DOC = SF2.F2_DOC
            and SD2.D2_SERIE = SF2.F2_SERIE

            left join SB1010 SB1
                ON B1_FILIAL = '      '
                AND SB1.B1_COD = SD2.D2_COD
                AND SB1.D_E_L_E_T_= ' '
            left join SF4010 SF4
                ON F4_FILIAL = '      '
                AND SF4.F4_CODIGO = SD2.D2_TES
                AND SF4.D_E_L_E_T_ = ' '
            LEFT JOIN SX5010 CFOP
                ON X5_FILIAL = '      '
                AND X5_TABELA = '13'
                AND X5_CHAVE = D2_CF
                AND CFOP.D_E_L_E_T_ = ' '
        
        LEFT JOIN SA1010 SA1
            ON A1_FILIAL = '      '
            AND SA1.A1_COD = SF2.F2_CLIENTE
            AND SA1.A1_LOJA = SF2.F2_LOJA
            AND SA1.D_E_L_E_T_= ' '
        LEFT JOIN SBM010 SBM
            ON BM_FILIAL = '      '
            AND BM_GRUPO = B1_GRUPO
            AND SBM.D_E_L_E_T_ = ' '
        LEFT JOIN SA3010 SA3
            ON A3_FILIAL = '      '
            AND A3_COD = F2_VEND1
            AND SA3.D_E_L_E_T_ = ' '
WHERE
        D2_TIPO NOT IN ('B', 'D')
    AND SD2.D_E_L_E_T_ = ' '
    AND SD2.D2_SERIE NOT IN ('003', '100')
