################################################
###     Par�metros obrigat�rios do Agent     ###
################################################
# Credenciais
gdc.username=suporte@unilinktransportes.com.br
gdc.password=3-28-237-168-58-165-250-28-90-69-56-249-79-192-121-211

# Pasta onde o arquivo zip ser� adicionado.
gdc.upload_url=https://secure-di.gooddata.com/project-uploads/kkchrzn0v7wdioourl7k8pvziyn4si8k/today/

# Nome do arquivo zip.
gdc.upload_archive=gooddataMNT.zip

# Par�metro respons�vel por verificar se ser� utilizado criptografia de senhas.
gdc.crypto=TRUE

# Backup
gdc.backup=TRUE

# Configura��o do caminho e job de ETL.
gdc.etl.process_url=https://analytics.totvs.com.br/gdc/projects/kkchrzn0v7wdioourl7k8pvziyn4si8k/dataload/processes/e800ce61-bf4f-4c40-a232-7d882a9dd32e/
gdc.etl.graph=Unilink/graph/executa_todos.grf

################################################
### Par�metros espec�ficos do FAST Analytics ###
################################################
# Configura��o do modo de carga do ETL (FullLoad / Incremental):
# gdc.etl.param.LOAD_MODE_FCT - Define o modo de carga dos datasets de fato.
# gdc.etl.param.LOAD_MODE_DIM - Define o modo de carga dos datasets de dimens�o.
#                               POSS�VEIS VALORES: FULL_LOAD
#                                                  INCREMENTAL
gdc.etl.param.LOAD_MODE_FCT=FULL_LOAD
gdc.etl.param.LOAD_MODE_DIM=FULL_LOAD

################################################
###   Configura��o para leitura de pastas    ###
################################################
#Diret�rio que o Agent ir� ler os arquivos.
filesystem.input_dir=./files/log
filesystem.input_dir=./files/Indicadores

#Extens�es v�lidas de arquivos.
filesystem.wildcard=agent.log*
filesystem.wildcard=teste-indicadores.xlsx

################################################
###    Configura��o de conex�o SQLServer     ###
################################################
jdbc.driver_path=jdbc/sqljdbc4.jar
jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
jdbc.url=jdbc:sqlserver://CV0QD8-127927-PR-PD.dbaas.clientes.tece1.local:37000;DatabaseName=CV0QD8_127927_PR_PD
jdbc.username=PROT62WUREAD
jdbc.password=243-112-83-83-208-49-22-192-144-84-187-165-41-66-121-92-12-105-107-184-255-11-205-129

param.START_DATE=CONVERT(varchar(8),DATEADD(month, -36, GETDATE()), 112)
param.FINAL_DATE=CONVERT(varchar(8), GETDATE(), 112)
param.EXTRACTION_DATE=CONVERT(varchar(8), GETDATE(), 112)

################################################
###     Configura��o de conex�o Oracle       ###
################################################
#jdbc.driver_path=jdbc/ojdbc6.jar
#jdbc.driver=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:sqlserver://DBAASLSN001067P.dbaas.intera.local:37066;DatabaseName=CV0QD8_112544_PROTHEUS_PRO
#jdbc.username=PRDI34BIREAD
#jdbc.password=19-254-208-70-130-202-201-242-203-77-94-97-204-235-58-0

#param.START_DATE=ADD_MONTHS(SYSDATE, -3)
#param.FINAL_DATE=SYSDATE
#param.EXTRACTION_DATE='20180507'

################################################
###   Exemplos de conex�o c/ banco de dados  ###
################################################
# Exemplos de Drivers
#
# IBM DB2
# jdbc.url=jdbc:sqlserver://DBAASLSN001067P.dbaas.intera.local:37066;DatabaseName=CV0QD8_112544_PROTHEUS_PRO
# jdbc.driver=com.ibm.db2.jdbc.app.DB2Driver
#
# Oracle Thin
# jdbc.url=jdbc:sqlserver://DBAASLSN001067P.dbaas.intera.local:37066;DatabaseName=CV0QD8_112544_PROTHEUS_PRO
# jdbc.driver=oracle.jdbc.driver.OracleDriver
#
# PostgreSQL (v7.0 and later)
# jdbc.url=jdbc:sqlserver://DBAASLSN001067P.dbaas.intera.local:37066;DatabaseName=CV0QD8_112544_PROTHEUS_PRO
# jdbc.driver=org.postgresql.Driver
#
# Microsoft SQL Server 2000 (Microsoft Driver)
# jdbc.url=jdbc:sqlserver://DBAASLSN001067P.dbaas.intera.local:37066;DatabaseName=CV0QD8_112544_PROTHEUS_PRO
# jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
# jdbc.driver_path=Diret�rio onde est� o arquivo jdbc.jar. Ex: "/jdbc/sqljdbc4.jar"

