SELECT
    RV_FILIAL,
    RV_COD,
    RV_DESC,
    RV_CODFOL,
    RV_TIPOCOD,
    RV_NATUREZ,
    C89_DESCRI,
    RV_INCIRF,
    C8T_DESCRI,
    RV_INCFGTS,
    C8T_DESCRI,
    RV_INCCP,
    C8T_DESCRI

FROM SRV010 SRV
    LEFT JOIN C89010 C89 ON (C89_CODIGO = RV_NATUREZ)
    LEFT JOIN C8T010 C8T ON (C8T_CODIGO = RV_INCCP) 
    LEFT JOIN C8U010 C8U ON (C8U_CODIGO = RV_INCIRF)
    LEFT JOIN V26010 V26 ON (V26_CODIGO = RV_INCFGTS)
WHERE
        RV_COD IN('029','030','091','401') /*Inserir aqui os codigos das verbas que deseja analisar*/
    AND RV_FILIAL = ' '
    AND SRV.D_E_L_E_T_ = ' '
    AND C8T.D_E_L_E_T_ = ' '
    AND C89.D_E_L_E_T_ = ' '
    AND RV_NATUREZ <> ''
GROUP BY
    RV_FILIAL,
    RV_COD,
    RV_DESC,
    RV_CODFOL,
    RV_TIPOCOD,
    RV_NATUREZ,
    C89_DESCRI,
    RV_INCIRF,
    C8T_DESCRI,
    RV_INCFGTS,
    C8T_DESCRI,
    RV_INCCP,
    C8T_DESCRI

ORDER BY RV_NATUREZ