SELECT DF1_DATPRC AS DT_PROG,
       DF1_HORPRC AS HR_PROG,
       CASE WHEN DTQ_SERTMS = '1' THEN 'COLETA'
       WHEN DTQ_SERTMS = '2' THEN 'TRANSPORTE'
       WHEN DTQ_SERTMS = '3' THEN 'ENTREGA'
       ELSE '' END AS 'OPERACAO',
       DF1_NUMAGE AS [AGENDTOTVS],
       DTR_VIAGEM AS [NUMVIAGEM],
       CASE WHEN DTQ_DATENC <> '' THEN 'OK'
      ELSE '' END AS RECEB_OS,
       DTR_CODVEI AS [NFROT_CAV],
       DA3.DA3_PLACA AS [PLACA_CAV],
       DA3.DA3_YATCOD AS [VEIC_ATTRAC],
       DTR_CODRB1 AS [NFROT_CAR],
       DA32.DA3_PLACA AS [PLACA_CAR],
     DA4_NOME AS MOTORISTA,
     ISNULL(RTRIM(DEV.A1_NOME),'')+' / '+ISNULL(RTRIM(DEST.A1_NOME),'') AS CLIENTE,
     ISNULL(DEV.A1_COD, '') AS DEV_COD, ISNULL(DEST.A1_COD, '') AS DEST_COD,
ISNULL((SELECT TOP 1 DTW_DATREA FROM DTW010 DTW WHERE DTW_FILIAL+DTW_VIAGEM = DTQ_FILIAL+DTQ_VIAGEM
AND DTW.D_E_L_E_T_ = '' AND DTW.DTW_ATIVID = '057'),'') AS [DTCHEGCLI],
ISNULL((SELECT TOP 1 DTW_HORREA FROM DTW010 DTW WHERE DTW_FILIAL+DTW_VIAGEM = DTQ_FILIAL+DTQ_VIAGEM
AND DTW.D_E_L_E_T_ = '' AND DTW.DTW_ATIVID = '057'),'') AS [HRCHEGCLI],
       DF1_YDSPOR AS [ORIGEM],
       DA8_DESC AS DESTINO,
       DF1_YDIBOO AS [BOOKING_DI],
       DT6_DOC AS NFE,   
       DF1_YCONT AS [Container]
FROM DTQ010 DTQ
JOIN DTR010 DTR ON (DTR_FILIAL+DTR_VIAGEM = DTQ_FILIAL+DTQ_VIAGEM
                    AND DTR.D_E_L_E_T_ = '')
JOIN DA8010 DA8 ON (DA8_FILIAL+DA8_COD =DTQ_FILIAL+DTQ_ROTA
                    AND DA8.D_E_L_E_T_ = '')
JOIN DUY010 DUY ON (DUY_FILIAL+DUY_GRPVEN = DA8_FILIAL+DA8_CDRORI
                    AND DUY.D_E_L_E_T_ = '')
JOIN DA3010 DA3 ON (DA3_COD = DTR_CODVEI
                    AND DA3.D_E_L_E_T_ = '')
JOIN DA3010 DA32 ON (DA32.DA3_COD = DTR_CODRB1
                     AND DA32.D_E_L_E_T_ = '')
JOIN DUP010 DUP ON (DUP_FILIAL+DUP_VIAGEM = DTR_FILIAL+DTR_VIAGEM
                    AND DUP.D_E_L_E_T_ = '')
JOIN DA4010 DA4 ON (DA4_FILIAL+DA4_COD = DUP_FILIAL+DUP_CODMOT
                    AND DA4.D_E_L_E_T_ = '')
JOIN DUD010 DUD ON (DUD_FILIAL+DUD_VIAGEM = DTQ_FILIAL+DTQ_VIAGEM
                    AND DUD.D_E_L_E_T_ = '')
JOIN DF1010 DF1 ON (DF1_FILIAL+DF1_DOC = DUD_FILIAL+DUD_DOC
                    AND DF1.D_E_L_E_T_ = '')
LEFT OUTER JOIN SA1010 DEST ON (DEST .A1_COD+DEST .A1_LOJA = DF1_CLIDES+DF1_LOJDES AND DEST.D_E_L_E_T_ = '')
LEFT OUTER JOIN SA1010 DEV ON (DEV.A1_COD+DEV.A1_LOJA = DF1_CLIDEV+DF1_LOJDEV AND DEV.D_E_L_E_T_ = '')
LEFT OUTER JOIN DTP010 DTP ON (DTP_FILIAL+DTP_VIAGEM =  DTQ_FILIAL+DTQ_VIAGEM AND DTP.D_E_L_E_T_ = '')
LEFT OUTER JOIN DT6010 DT6 ON ( DT6_FILIAL+DT6_LOTNFC = DTP_FILIAL+DTP_LOTNFC AND DT6.D_E_L_E_T_ = '')
LEFT OUTER JOIN DTC010 DTC ON ( DTC_FILIAL+DTC_LOTNFC = DTP_FILIAL+DTP_LOTNFC AND DTC.D_E_L_E_T_ = '')
WHERE DTQ.D_E_L_E_T_ = ''
