SELECT 
DF1_NUMAGE AS Agendamento, 
DF1_ITEAGE as Item, 
CAST(DF0_DATCAD AS DATETIME) AS Emissao, 

year(DF0_DATCAD) AS Emissao_ANO, 
month(DF0_DATCAD) AS Emissao_MES,
DF1_CLIDEV as Devedor_QTD,

A1_NOME as Devedor,
CASE   
    WHEN DF0_STATUS = '1' THEN 'A Confirmar'   
    WHEN DF0_STATUS = '2' THEN 'Confirmado'   
    WHEN DF0_STATUS = '3' THEN 'Em Processo'   
    WHEN DF0_STATUS = '4' THEN 'Encerrado'   
    WHEN DF0_STATUS = '5' THEN 'Planejado'   
    WHEN DF0_STATUS = '9' THEN 'Cancelado'   
END   
AS Status,
DF1_YCONT as Container, 
DF1_YOSCLI as OS_Cliente, 
EST_COL as UF_Coleta, 
MUN_COL as Mun_Coleta, 
EST_ENT as UF_Entrega, 
MUN_ENT as Mun_Entrega,
DTC_NUMNFC as Nota_Cli,
DTC_VALOR as Nota_Valor,
DT6_DOC as NFe_CTe,
DT6_SERIE as Serie,
DT6_VALTOT as Valor_CTe,
DF1_DOC as Coleta,
VGA_VGA as Viagem,
VGA_MOTNOM as Motorista,
VGA_CODVEI as Frota,
VGA_VEIPLA as Placa




FROM DF0010 [NOLOCK]

INNER JOIN DF1010 ON DF0_FILIAL+DF0_NUMAGE=DF1_FILIAL+DF1_NUMAGE
INNER JOIN SA1010  ON DF1_CLIDEV+DF1_LOJDEV=A1_COD+A1_LOJA
INNER JOIN (SELECT  DUY_GRPVEN AS GRP_COL, DUY_EST AS EST_COL, DUY_DESCRI MUN_COL FROM DUY010) AS REG_COL
ON GRP_COL=DF1_CDRORI
INNER JOIN (SELECT  DUY_GRPVEN AS GRP_ENT, DUY_EST AS EST_ENT, DUY_DESCRI MUN_ENT FROM DUY010)  AS REG_ENT
ON GRP_ENT=DF1_CDRDES
LEFT JOIN DTC010  ON DF1_FILDOC+DF1_DOC=DTC_FILORI+DTC_NUMSOL
LEFT JOIN DT6010  ON DTC_FILDOC+DTC_DOC+DTC_SERIE=DT6_FILDOC+DT6_DOC+DT6_SERIE
LEFT JOIN 
(SELECT DUD_FILORI AS VGA_FIL, 
DUD_FILDOC AS VGA_FILDOC, 
DUD_DOC AS VGA_DOC, 
DUD_SERIE AS VGA_SERIE, 
DUD_VIAGEM  AS VGA_VGA, 
DTR_CODVEI AS VGA_CODVEI, 
DA3_VEI.DA3_PLACA AS VGA_VEIPLA,
DTR_CODRB1 AS VGA_CODRB1,
DA3_RB1.DA3_PLACA AS VGA_DB1PLA,
DTR_CODRB2 AS VGA_CODRB2,
DA3_RB2.DA3_PLACA AS VGA_RB2PLA,
DTR_CODRB3 AS VGA_CODRB3, 
DA3_RB3.DA3_PLACA AS VGA_RB3PLA,
DUP_CODMOT AS VGA_MOT, 
DA4_NOME AS VGA_MOTNOM

FROM DUD010

LEFT JOIN DTR010 ON DUD_FILORI + DUD_VIAGEM = DTR_FILORI + DTR_VIAGEM
LEFT JOIN DUP010 ON DUD_FILORI + DUD_VIAGEM = DUP_FILORI + DUP_VIAGEM
LEFT JOIN DA4010 ON DA4_COD  = DUP_CODMOT 
LEFT JOIN DA3010 AS DA3_VEI ON DA3_VEI.DA3_COD  = DTR_CODVEI 
LEFT JOIN DA3010 AS DA3_RB1 ON DA3_RB1.DA3_COD  = DTR_CODRB1 
LEFT JOIN DA3010 AS DA3_RB2 ON DA3_RB2.DA3_COD  = DTR_CODRB2 
LEFT JOIN DA3010 AS DA3_RB3 ON DA3_RB3.DA3_COD  = DTR_CODRB3
WHERE DUP010.D_E_L_E_T_=' ' ) AS VGA
ON VGA_DOC + VGA_SERIE = SUBSTRING(CONCAT(isnull(DT6_DOC,''),DF1_DOC),1,9)+isnull(DT6_SERIE,'COL')
WHERE DTC010.D_E_L_E_T_=' '