	SELECT 'P |01|01010101' AS BK_FILIAL,'010101' AS COD_FILIAL,'Matriz' AS DESC_FILIAL,'01' AS COD_UNINEG,'Unilink' AS DESC_UNINEG from SRC010
UNION 
	SELECT 'P |01|01010102' AS BK_FILIAL,'010102' AS COD_FILIAL,'Pecem' AS DESC_FILIAL,'01' AS COD_UNINEG,'Unilink' AS DESC_UNINEG from SRC010
UNION 
	SELECT 'P |01|01      ' AS BK_FILIAL,'01      ' AS COD_FILIAL,'Unilink - COMPARTILHADA' AS DESC_FILIAL,'' AS COD_UNINEG,'' AS DESC_UNINEG from SRC010
UNION 
	SELECT 'P |01|0101    ' AS BK_FILIAL,'0101    ' AS COD_FILIAL,'Unilink - COMPARTILHADA' AS DESC_FILIAL,'' AS COD_UNINEG,'' AS DESC_UNINEG from SRC010
UNION 
	SELECT 'P |01|010101  ' AS BK_FILIAL,'010101  ' AS COD_FILIAL,'Unilink - COMPARTILHADA' AS DESC_FILIAL,'' AS COD_UNINEG,'' AS DESC_UNINEG from SRC010
UNION
	SELECT 'P |01||' as BK_FILIAL,'01 - INDEFINIDO' as COD_FILIAL,'01 - INDEFINIDO' as DESC_FILIAL,'01 - INDEFINIDO' as COD_UNINEG,'01 - INDEFINIDO' as DESC_UNINEG from SRC010















