SELECT
    'P |01|01' AS BK_EMPRESA,
    case when SD1.D1_FILIAL is null then 'P |01||' else 'P |01|01'+ CAST(SD1.D1_FILIAL as char (6)) end as BK_FILIAL,
    'P |01|SB1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SB1.B1_FILIAL, ' '))+'|'+RTRIM(COALESCE(SD1.D1_COD, ' ')), ' '), '|') AS BK_ITEM,
    'P |01|SBM010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SBM.BM_FILIAL, ' '))+'|'+RTRIM(COALESCE(SB1.B1_GRUPO, ' ')), ' '), '|') AS BK_GRUPO_ESTOQUE,
    'P |01|SA2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SA2.A2_FILIAL, ' '))+'|'+RTRIM(COALESCE(SD1.D1_FORNECE, ' '))+RTRIM(COALESCE(SD1.D1_LOJA, ' ')), ' '), '|') AS BK_FORNECEDOR,
    'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(GRPFOR.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(SA2.A2_GRUPO, ' ')), ' '), '|') AS BK_GRUPO_FORNECEDOR,
    'P |01|SA4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SA4.A4_FILIAL, ' '))+'|'+RTRIM(COALESCE(SF1.F1_TRANSP, ' ')), ' '), '|') AS BK_TRANSPORTADORA,
    'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(FAMAT.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(SB1.B1_TIPO, ' ')), ' '), '|') AS BK_FAMILIA_MATERIAL,
    'P |01|ACU010|'+ COALESCE(NULLIF(RTRIM(COALESCE(ACU.ACU_FILIAL, ' '))+'|'+RTRIM(COALESCE(ACU.ACU_COD, ' ')), ' '), '|') AS BK_FAMILIA_COMERCIAL,
    'P |01|SY1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SY1.Y1_FILIAL, ' '))+'|'+RTRIM(COALESCE(SC7.C7_COMPRA, ' ')), ' '), '|') AS BK_COMPRADOR,
    'P |01|SE4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SE4.E4_FILIAL, ' '))+'|'+RTRIM(COALESCE(SF1.F1_COND, ' ')), ' '), '|') AS BK_CONDICAO_DE_PAGAMENTO,
    'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CFOP.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(SD1.D1_CF, ' ')), ' '), '|') AS BK_CFOP,
    'P |01|CTT010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTT.CTT_FILIAL, ' '))+'|'+RTRIM(COALESCE(SD1.D1_CC, ' ')), ' '), '|') AS BK_CENTRO_DE_CUSTO,
    'P |01|SF4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SF4.F4_FILIAL, ' '))+'|'+RTRIM(COALESCE(SD1.D1_TES, ' ')), ' '), '|') AS BK_TES,
    'P |01|SAH010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SAH.AH_FILIAL, ' '))+'|'+RTRIM(COALESCE(SD1.D1_UM, ' ')), ' '), '|') AS BK_UNIDADE_DE_MEDIDA,
    case when SA2.A2_COD_MUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SA2.A2_EST, ' ')), ' '), '|') else 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SA2.A2_EST, ' '))+RTRIM(COALESCE(SA2.A2_COD_MUN, ' ')), ' '), '|') end as BK_REGIAO,
    
    CASE
        WHEN (SC7.C7_QUJE > 0)
            AND (SC7.C7_QUJE < SC7.C7_QUANT) THEN 'P |'+ COALESCE(NULLIF(RTRIM(COALESCE('R', ' ')), ' '), '|')
        WHEN (SC7.C7_QUJE >= SC7.C7_QUANT) THEN 'P |'+ COALESCE(NULLIF(RTRIM(COALESCE('I', ' ')), ' '), '|')
        ELSE 'P |'+'|'
    END AS BK_SITUACAO_COMPRA,
    
    'P |01|CTD010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTD.CTD_FILIAL, ' '))+'|'+RTRIM(COALESCE(SD1.D1_ITEMCTA, ' ')), ' '), '|') AS BK_ITEM_CONTABIL,	 
    SD1.D1_PEDIDO PEDIDO,
    SD1.D1_ITEM SEQCIA,
    SD1.D1_DOC NUMNF,
    SD1.D1_EMISSAO DATANF,
    SD1.D1_DTDIGIT AS DATA,
    SD1.D1_SERIE SERNF,
    SD1.D1_REMITO REMITO,
    SD1.D1_SERIREM SERREM,
    SD1.D1_ITEMREM ITEREM,
    SD1.D1_QUANT QRECEB,
    SD1.D1_TOTAL VRECEB,
    SC7.C7_NUMSC ORDEM,
    SC7.C7_EMISSAO DTEPED,
    SC7.C7_DATPRF DTPREV,
    SC1.C1_EMISSAO DTEORD,
    
    CASE
        WHEN (COALESCE(SC7.C7_DATPRF, ' ') = ' ')
            OR (SC7.C7_DATPRF = NULL)
            OR (COALESCE(SD1.D1_DTDIGIT, ' ') = ' ')
            OR (SD1.D1_DTDIGIT = NULL)
            OR (SD1.D1_DTDIGIT > SC7.C7_DATPRF) THEN 0
        ELSE DATEDIFF(DD, SD1.D1_DTDIGIT, SC7.C7_DATPRF)
    END AS QDIAAN,
    
    CASE WHEN (COALESCE(SC7.C7_DATPRF, ' ') = ' ')
            OR (SC7.C7_DATPRF = NULL)
            OR (COALESCE(SD1.D1_DTDIGIT, ' ') = ' ')
            OR (SD1.D1_DTDIGIT = NULL)
            OR (SC7.C7_DATPRF > SD1.D1_DTDIGIT) THEN 0
        ELSE DATEDIFF(DD, SC7.C7_DATPRF, SD1.D1_DTDIGIT)
    END AS QDIAAT,
    
    CASE WHEN DATEDIFF(DD, SD1.D1_DTDIGIT, SC7.C7_DATPRF) > 0 THEN 1 ELSE 0 END AS QRECAN,
    CASE WHEN DATEDIFF(DD, SC7.C7_DATPRF, SD1.D1_DTDIGIT) < 0 THEN 1 ELSE 0 END AS QRECAT,
    CASE WHEN (DATEDIFF(DD, SD1.D1_DTDIGIT, SC7.C7_DATPRF) = 0) AND (DATEDIFF(DD, SC7.C7_DATPRF, SD1.D1_DTDIGIT) = 0) THEN 1 ELSE 0 END AS QRECDT,
    CASE WHEN (SD1.D1_QUANT >= SC7.C7_QUANT) THEN 1 ELSE 0 END AS QRECUN
FROM SD1010 SD1
    LEFT JOIN SB1010 SB1
        ON SB1.B1_FILIAL = '      '
        AND SB1.B1_COD = SD1.D1_COD
        AND SB1.D_E_L_E_T_ = ' '
        
        LEFT JOIN SBM010 SBM
            ON SBM.BM_FILIAL = SB1.B1_FILIAL
            AND SBM.BM_GRUPO = SB1.B1_GRUPO
            AND SBM.D_E_L_E_T_ = ' '
        LEFT JOIN SX5010 FAMAT
            ON FAMAT.X5_FILIAL = '      '
            AND FAMAT.X5_TABELA = '02'
            AND FAMAT.X5_CHAVE = B1_TIPO
            AND FAMAT.D_E_L_E_T_ = ' '

    LEFT JOIN SA2010 SA2
        ON SA2.A2_FILIAL = '      '
        AND SA2.A2_COD = SD1.D1_FORNECE
        AND SA2.A2_LOJA = SD1.D1_LOJA
        AND SA2.D_E_L_E_T_ = ' '

        LEFT JOIN SX5010 GRPFOR
            ON GRPFOR.X5_FILIAL = '      '
            AND GRPFOR.X5_TABELA = 'Y7'
            AND GRPFOR.X5_CHAVE = SA2.A2_GRUPO
            AND GRPFOR.D_E_L_E_T_ = ' '
    
    LEFT JOIN CTT010 CTT
        ON CTT.CTT_FILIAL = SUBSTRING(SD1.D1_FILIAL, 1, 4)
        AND CTT.CTT_CUSTO = SD1.D1_CC
        AND CTT.D_E_L_E_T_ = ' '
    LEFT JOIN CTD010 CTD
        ON CTD.CTD_FILIAL = '      '
        AND CTD.CTD_ITEM = SD1.D1_ITEMCTA
        AND CTD.D_E_L_E_T_ = ' '
    LEFT JOIN SF1010 SF1
        ON SF1.F1_FILIAL = SD1.D1_FILIAL
        AND SF1.F1_DOC = SD1.D1_DOC
        AND SF1.F1_SERIE = SD1.D1_SERIE
        AND SF1.F1_FORNECE = SD1.D1_FORNECE
        AND SF1.F1_LOJA = SD1.D1_LOJA
        AND SF1.D_E_L_E_T_ = ' '
        
        LEFT JOIN SA4010 SA4
            ON SA4.A4_FILIAL = '      '
            AND SA4.A4_COD = SF1.F1_TRANSP
            AND SA4.D_E_L_E_T_ = ' '
        LEFT JOIN SE4010 SE4
            ON SE4.E4_FILIAL = '      '
            AND SE4.E4_CODIGO = SF1.F1_COND
            AND SE4.D_E_L_E_T_ = ' '
    
    LEFT JOIN ACV010 ACV
        ON ACV.ACV_FILIAL = SUBSTRING(SD1.D1_FILIAL, 1, 4)
        AND ACV.ACV_CODPRO = SD1.D1_COD
        AND ACV.D_E_L_E_T_ = ' '
        
        LEFT JOIN ACU010 ACU
            ON ACU.ACU_FILIAL = ACV_FILIAL
            AND ACU.ACU_COD = ACV.ACV_CATEGO
            AND ACU.D_E_L_E_T_ = ' '
    
    LEFT JOIN SC7010 SC7
        ON SC7.C7_FILIAL = SD1.D1_FILIAL
        AND SC7.C7_NUM = SD1.D1_PEDIDO
        AND SC7.C7_ITEM = SD1.D1_ITEMPC
        AND SC7.C7_PRODUTO = SD1.D1_COD
        AND SC7.D_E_L_E_T_ = ' '

        LEFT JOIN SC1010 SC1
            ON SC1.C1_FILIAL = SC7.C7_FILIAL
            AND SC1.C1_NUM = SC7.C7_NUMSC
            AND SC1.C1_ITEM = SC7.C7_ITEMSC
            AND SC1.C1_PRODUTO = SC7.C7_PRODUTO
            AND SC1.D_E_L_E_T_ = ' '
        LEFT JOIN SY1010 SY1
            ON SY1.Y1_FILIAL = SUBSTRING(SC7.C7_FILIAL, 1, 2)
            AND SY1.Y1_COD = SC7.C7_COMPRA
    
    LEFT JOIN SX5010 CFOP
        ON CFOP.X5_FILIAL = '      '
        AND CFOP.X5_TABELA = '13'
        AND CFOP.X5_CHAVE = SD1.D1_CF
        AND CFOP.D_E_L_E_T_ = ' '
    LEFT JOIN SF4010 SF4
        ON SF4.F4_FILIAL = '      '
        AND SF4.F4_CODIGO = SD1.D1_TES
        AND SF4.D_E_L_E_T_ = ' '
    LEFT JOIN SAH010 SAH
        ON SAH.AH_FILIAL = '      '
        AND SAH.AH_UNIMED = SD1.D1_UM
        AND SAH.D_E_L_E_T_ = ' '
WHERE
        SD1.D1_DTDIGIT BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
    and SD1.D1_ORIGLAN <> 'LF'
    and SD1.D1_TIPO NOT IN ('D', 'B')
    and SD1.D_E_L_E_T_ = ' '
