SELECT
    'P |01|01' AS BK_EMPRESA,
    
    CASE
        WHEN D1_FILIAL IS NULL THEN 'P |01||'
        ELSE 'P |01|01'+ CAST(D1_FILIAL AS CHAR (6))
    END AS BK_FILIAL,
    
    D1_DTDIGIT AS DATA_DE_DEVOLUCAO,
    'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CFOP.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(D1_CF, ' ')), ' '), '|') AS BK_CFOP,
    D1_SERIE AS SERIE_DOCUMENTO_CLIENTE,
    D1_DOC AS NUMERO_DOCUMENTO_CLIENTE,
    F2_SERIE AS SERIE_NOTA_FISCAL,
    F2_DOC AS NUMERO_DA_NOTA_FISCAL,
    D1_ITEM AS NUMERO_DO_ITEM_DO_DOCUMENTO,
    D1_DOC + D1_SERIE AS NUMERO_DO_ITEM_DA_NF,
    D1_REMITO AS NUMERO_DO_REMITO,
    D1_SERIREM AS SERIE_DO_REMITO,
    D1_ITEMREM AS ITEM_DO_REMITO,
    
    'P |01|SF4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(F4_FILIAL, ' '))+'|'+RTRIM(COALESCE(D1_TES, ' ')), ' '), '|') AS BK_TES,
    'P |01|SE4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(E4_FILIAL, ' '))+'|'+RTRIM(COALESCE(F2_COND, ' ')), ' '), '|') AS BK_CONDICAO_DE_PAGAMENTO,
    'P |01|SB1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(B1_FILIAL, ' '))+'|'+RTRIM(COALESCE(D1_COD, ' ')), ' '), '|') AS BK_ITEM,
    'P |01|SBM010|'+ COALESCE(NULLIF(RTRIM(COALESCE(BM_FILIAL, ' '))+'|'+RTRIM(COALESCE(B1_GRUPO, ' ')), ' '), '|') AS BK_GRUPO_ESTOQUE,
    'P |01|SA3010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A3_FILIAL, ' '))+'|'+RTRIM(COALESCE(F2_VEND1, ' ')), ' '), '|') AS BK_VENDEDOR,
    'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(D1_FORNECE, ' '))+RTRIM(COALESCE(D1_LOJA, ' ')), ' '), '|') AS BK_CLIENTE,
    'P |01|SAH010|'+ COALESCE(NULLIF(RTRIM(COALESCE(AH_FILIAL, ' '))+'|'+RTRIM(COALESCE(D1_UM, ' ')), ' '), '|') AS BK_UNIDADE_DE_MEDIDA,
    
    CASE
        WHEN SA1.A1_COD_MUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' ')), ' '), '|')
        ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' '))+RTRIM(COALESCE(A1_COD_MUN, ' ')), ' '), '|')
    END AS BK_REGIAO,
    
    'P |01|CTD010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTD_FILIAL, ' '))+'|'+RTRIM(COALESCE(D1_ITEMCTA, ' ')), ' '), '|') AS BK_ITEM_CONTABIL,
    D1_QUANT AS QTDE_DEVOLVIDA_ITEM,
    D1_TOTAL+D1_VALIPI+D1_ICMSRET AS VL_DEVOLUCAO_TOTAL,
    D1_VALICM AS VL_ICMS_DEVOLUCAO,
    D1_VALIPI AS VL_IPI_DEVOLUCAO,
    (D1_TOTAL - (D1_VALICM + D1_VALIMP5 + D1_VALIMP6 + D1_VALDESC)) AS VL_DEVOLUCAO_LIQUIDA,
    D1_TOTAL - D1_VALDESC AS VL_DEVOLUCAO_MERCADORIA,
    D1_VALIMP6 AS VL_PIS_DEVOLUCAO,
    D1_VALIMP5 AS VL_COFINS_DEVOLUCAO,
    D1_ICMSRET AS VL_ICMS_SUBST_DEVOLUCAO,
    D1_VALDESC AS VL_DESCONTO_DEVOLUCAO,
    D1_VALINS AS VL_INSS_DEVOLUCAO

FROM SD1010 SD1
    INNER JOIN SF2010 SF2
        ON SF2.D_E_L_E_T_ = ' '
        AND SF2.F2_FILIAL = SD1.D1_FILIAL
        AND SF2.F2_DOC = SD1.D1_NFORI
        AND SF2.F2_SERIE = SD1.D1_SERIORI
        AND SF2.F2_CLIENTE = SD1.D1_FORNECE
        AND SF2.F2_LOJA = SD1.D1_LOJA
    INNER JOIN SB1010 SB1
        ON SB1.B1_FILIAL = '      '
        AND SB1.B1_COD = SD1.D1_COD
        AND SB1.D_E_L_E_T_ = ' '
    LEFT JOIN SF4010 SF4
        ON SF4.F4_FILIAL = '      '
        AND SF4.F4_CODIGO = SD1.D1_TES
        AND SF4.D_E_L_E_T_ = ' '
        
        LEFT JOIN SE4010 SE4 
            ON SE4.E4_FILIAL = '      '
            AND SE4.E4_CODIGO = SF2.F2_COND
            AND SE4.D_E_L_E_T_ = ' '
        LEFT JOIN SA3010 SA3
            ON SA3.A3_FILIAL = '      '
            AND SA3.A3_COD = SF2.F2_VEND1
            AND SA3.D_E_L_E_T_ = ' '
        LEFT JOIN SA1010 SA1
            ON SA1.A1_FILIAL = '      '
            AND SA1.A1_COD = SF2.F2_CLIENTE
            AND SA1.A1_LOJA = SF2.F2_LOJA
            AND SA1.D_E_L_E_T_= ' '
    
    LEFT JOIN SBM010 SBM
        ON SBM.BM_FILIAL = SB1.B1_FILIAL
        AND SBM.BM_GRUPO = SB1.B1_GRUPO
        AND SBM.D_E_L_E_T_ = ' '
    LEFT JOIN CTD010 CTD
        ON CTD.CTD_FILIAL = '      '
        AND CTD.CTD_ITEM = SD1.D1_ITEMCTA
        AND CTD.D_E_L_E_T_ = ' '
    LEFT JOIN SAH010 SAH
        ON SAH.AH_FILIAL = '      '
        AND SAH.AH_UNIMED = SD1.D1_UM
        AND SAH.D_E_L_E_T_ = ' '
    LEFT JOIN SX5010 CFOP
        ON CFOP.X5_FILIAL = '      '
        AND CFOP.X5_TABELA = '13'
        AND CFOP.X5_CHAVE = SD1.D1_CF
        AND CFOP.D_E_L_E_T_ = ' '
WHERE
        SD1.D1_DTDIGIT BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
    AND SD1.D_E_L_E_T_ = ' '
    AND SD1.D1_SERIE NOT IN ('003', '100')
