  SELECT
    'P |01|01' AS BK_EMPRESA,
    CASE WHEN CT2_FILIAL IS NULL THEN 'P |01||' ELSE 'P |01|01'+ CAST(CT2_FILIAL AS CHAR (6)) END AS BK_FILIAL,
    'P |01|CT1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CT1_FILIAL, ' '))+'|'+RTRIM(COALESCE(CT2_DEBITO, ' ')), ' '), '|') AS BK_CONTA,
    CASE WHEN CT2_FILORI IS NULL THEN 'P |01||' ELSE 'P |01|01'+ CAST(CT2_FILORI AS CHAR (6)) END AS BK_FILIAL_ORIGEM,
    'P |01|CTD010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTD_FILIAL, ' '))+'|'+RTRIM(COALESCE(CT2_ITEMD, ' ')), ' '), '|') AS BK_ITEM_CONTABIL,
    'P |01|CTT010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTT_FILIAL, ' '))+'|'+RTRIM(COALESCE(CT2_CCD, ' ')), ' '), '|') AS BK_CENTRO_CUSTO,
    'P |01|CTH010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTH_FILIAL, ' '))+'|'+RTRIM(COALESCE(CT2_CLVLDB, ' ')), ' '), '|') AS BK_CLASSE_VALOR,
    CT2_DATA AS DATA,
    CT2_TPSALD AS TPSALD,
    CT2_DC AS DC,
    CT2_LOTE AS LOTE,
    CT2_SBLOTE AS SUBLOTE,
    CT2_DOC AS DOC,
    CT2_LINHA AS LINHA,
    CT2_CREDIT AS CONTA_PARTIDA,
    CT2_HIST AS HISTORICO,
    CT2_SEQHIS AS SEQUENCIA_HISTORICO,
    CT2_SEQLAN AS SEQUENCIA_AUXILIAR,
    CAST(COALESCE(CT2_VALOR, 0) AS DECIMAL(16, 2)) AS VALOR_DEBITO,
    '0.00' AS VALOR_CREDITO,
    '1' AS TIPOLAN
  FROM CT2010 CT2
    LEFT JOIN CT1010 CT1 ON CT1_CONTA = CT2_DEBITO
    AND CT1_FILIAL = CT2_FILIAL
    AND CT1.D_E_L_E_T_ = ' '
    LEFT JOIN CTD010 CTD ON CTD_FILIAL = CT2_FILIAL
    AND CTD_ITEM = CT2_ITEMD
    AND CTD.D_E_L_E_T_ = ' '
    LEFT JOIN CTT010 CTT ON CTT_FILIAL = CT2_FILORI
    AND CTT_CUSTO = CT2_CCD
    AND CTT.D_E_L_E_T_ = ' '
    LEFT JOIN CTH010 CTH ON CTH_FILIAL = CT2_FILIAL
    AND CTH_CLVL = CT2_CLVLDB
    AND CTH.D_E_L_E_T_ = ' '
  WHERE CT2_DATA between <<START_DATE>> and <<FINAL_DATE>>
    AND (CT2_DC = '1' OR CT2_DC = '3')
    AND CT2_VALOR <> '0'
    AND CT2.D_E_L_E_T_ = ' '
UNION
  SELECT
    'P |01|01' AS BK_EMPRESA,
    CASE WHEN CT2_FILIAL IS NULL THEN 'P |01||' ELSE 'P |01|01'+ CAST(CT2_FILIAL AS CHAR (6)) END AS BK_FILIAL,
    'P |01|CT1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CT1_FILIAL, ' '))+'|'+RTRIM(COALESCE(CT2_CREDIT, ' ')), ' '), '|') AS BK_CONTA,
    CASE WHEN CT2_FILORI IS NULL THEN 'P |01||' ELSE 'P |01|01'+ CAST(CT2_FILORI AS CHAR (6)) END AS BK_FILIAL_ORIGEM,
    'P |01|CTD010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTD_FILIAL, ' '))+'|'+RTRIM(COALESCE(CT2_ITEMC, ' ')), ' '), '|') AS BK_ITEM_CONTABIL,
    'P |01|CTT010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTT_FILIAL, ' '))+'|'+RTRIM(COALESCE(CT2_CCC, ' ')), ' '), '|') AS BK_CENTRO_CUSTO,
    'P |01|CTH010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTH_FILIAL, ' '))+'|'+RTRIM(COALESCE(CT2_CLVLCR, ' ')), ' '), '|') AS BK_CLASSE_VALOR,
    CT2_DATA AS DATA,
    CT2_TPSALD AS TPSALD,
    CT2_DC AS DC,
    CT2_LOTE AS LOTE,
    CT2_SBLOTE AS SUBLOTE,
    CT2_DOC AS DOC,
    CT2_LINHA AS LINHA,
    CT2_DEBITO AS CONTA_PARTIDA,
    CT2_HIST AS HISTORICO,
    CT2_SEQHIS AS SEQUENCIA_HISTORICO,
    CT2_SEQLAN AS SEQUENCIA_AUXILIAR,
    '0.00' AS VALOR_DEBITO,
    CAST(COALESCE(CT2_VALOR, 0) AS DECIMAL(16, 2)) AS VALOR_CREDITO,
    '2' AS TIPOLAN
  FROM CT2010 CT2
    LEFT JOIN CT1010 CT1 ON CT1_CONTA = CT2_CREDIT
    AND CT1_FILIAL = CT2_FILIAL
    AND CT1.D_E_L_E_T_ = ' '
    LEFT JOIN CTD010 CTD ON CTD_FILIAL = CT2_FILIAL
    AND CTD_ITEM = CT2_ITEMC
    AND CTD.D_E_L_E_T_ = ' '
    LEFT JOIN CTT010 CTT ON CTT_FILIAL = CT2_FILORI
    AND CTT_CUSTO = CT2_CCC
    AND CTT.D_E_L_E_T_ = ' '
    LEFT JOIN CTH010 CTH ON CTH_FILIAL = CT2_FILIAL
    AND CTH_CLVL = CT2_CLVLCR
    AND CTH.D_E_L_E_T_ = ' '
  WHERE CT2_DATA between <<START_DATE>> and <<FINAL_DATE>>
    AND (CT2_DC = '2' OR CT2_DC = '3')
    AND CT2_VALOR <> '0'
    AND CT2.D_E_L_E_T_ = ' '