SELECT 'P |01|01' AS BK_EMPRESA,
       CASE
           WHEN D2_FILIAL IS NULL THEN 'P |01||'
           ELSE 'P |01|01'+ CAST(D2_FILIAL AS CHAR (6))
       END AS BK_FILIAL,
       F2_SERIE AS SERIE_DA_NOTA_FISCAL,
       F2_DOC AS NUMERO_DA_NOTA_FISCAL,
       D2_PEDIDO AS NUMERO_PEDIDO_VENDA,
       D2_ITEM AS NUMERO_ITEM,
       CASE
           WHEN LTRIM(RTRIM(F2_EMISSAO)) = ' ' THEN ' '
           ELSE F2_EMISSAO
       END AS DATA_DE_EMISSAO,
       CASE
           WHEN LTRIM(RTRIM(F2_EMINFE)) = ' ' THEN ' '
           ELSE F2_EMINFE
       END AS DATA_SAIDA_NF,
       F2_TPFRETE AS TIPO_DE_FRETE,
       D2_TIPO AS TIPO_DE_NOTA_FISCAL,
       D2_ORIGLAN AS ORIGEM_DO_LANCAMENTO,
       'P |01|SB1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(B1_FILIAL, ' '))+'|'+RTRIM(COALESCE(D2_COD, ' ')), ' '), '|') AS BK_ITEM,
       'P |01|SBM010|'+ COALESCE(NULLIF(RTRIM(COALESCE(BM_FILIAL, ' '))+'|'+RTRIM(COALESCE(B1_GRUPO, ' ')), ' '), '|') AS BK_GRUPO_ESTOQUE,
       'P |01|SA3010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A3_FILIAL, ' '))+'|'+RTRIM(COALESCE(F2_VEND1, ' ')), ' '), '|') AS BK_VENDEDOR,
       'P |01|SF4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(F4_FILIAL, ' '))+'|'+RTRIM(COALESCE(D2_TES, ' ')), ' '), '|') AS BK_TES,
       'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CFOP.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(D2_CF, ' ')), ' '), '|') AS BK_CFOP,
       'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(A1_TIPO, ' ')), ' '), '|') AS BK_GRUPO_CLIENTE,
       'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(D2_CLIENTE, ' '))+RTRIM(COALESCE(D2_LOJA, ' ')), ' '), '|') AS BK_CLIENTE,
       CASE
           WHEN A1_COD_MUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' ')), ' '), '|')
           ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' '))+RTRIM(COALESCE(A1_COD_MUN, ' ')), ' '), '|')
       END AS BK_REGIAO,
       'P |01|SE4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(E4_FILIAL, ' '))+'|'+RTRIM(COALESCE(F2_COND, ' ')), ' '), '|') AS BK_CONDICAO_DE_PAGAMENTO,
       'P |01|ACY010|'+ COALESCE(NULLIF(RTRIM(COALESCE(ACY_FILIAL, ' '))+'|'+RTRIM(COALESCE(A1_GRPVEN, ' ')), ' '), '|') AS BK_REGIAO_COMERCIAL,
       'P |01|SAH010|'+ COALESCE(NULLIF(RTRIM(COALESCE(AH_FILIAL, ' '))+'|'+RTRIM(COALESCE(D2_UM, ' ')), ' '), '|') AS BK_UNIDADE_DE_MEDIDA,
       'P |01|CTD010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTD_FILIAL, ' '))+'|'+RTRIM(COALESCE(D2_ITEMCC, ' ')), ' '), '|') AS BK_ITEM_CONTABIL,
       CAST(COALESCE(D2_VALBRUT, 0) AS DECIMAL(14, 2)) AS VL_FATURAMENTO_TOTAL,
       CAST(COALESCE(D2_VALICM, 0) AS DECIMAL(14, 2)) AS VL_ICMS_FATURAMENTO,
       CAST(COALESCE(D2_VALIPI, 0) AS DECIMAL(14, 2)) AS VL_IPI_FATURAMENTO,
       CAST(COALESCE(D2_VALFRE, 0) AS DECIMAL(14, 2)) AS VL_FRETE_NF,
       CAST(COALESCE(D2_DESPESA, 0) AS DECIMAL(14, 2)) AS VL_DESPESA,
       CAST(COALESCE(D2_TOTAL, 0) AS DECIMAL(14, 2)) AS VL_FATURAMENTO_MERCADORIA,
       CAST(COALESCE(D2_VALIMP6, 0) AS DECIMAL(14, 2)) AS VL_PIS_FATURAMENTO,
       CAST(COALESCE(D2_VALIMP5, 0) AS DECIMAL(14, 2)) AS VL_COFINS_FATURAMENTO,
       CAST(COALESCE(D2_QUANT, 0) AS DECIMAL(13, 3)) AS QTD_FATURADA_ITEM,
       CAST(COALESCE(D2_VALISS, 0) AS DECIMAL(14, 2)) AS VL_ISS_FATURAMENTO,
       CAST(COALESCE(D2_ICMSRET, 0) AS DECIMAL(14, 2)) AS VL_ICMS_SUBST_FATURAMENTO,
       CAST(COALESCE(D2_DESCON, 0) AS DECIMAL(12, 2)) AS VL_DESCONTO_FATURAMENTO,
       CAST(COALESCE(D2_VALIRRF, 0) AS DECIMAL(14, 2)) AS VL_IRF_FATURAMENTO,
       CAST(COALESCE(D2_VALINS, 0) AS DECIMAL(14, 2)) AS VL_INSS_FATURAMENTO,
       CAST(COALESCE(D2_PESO * D2_QUANT, 0) AS DECIMAL(12, 4)) AS PESO_LIQUIDO,
       CAST(COALESCE(B1_PESBRU * D2_QUANT, 0) AS DECIMAL(12, 4)) AS PESO_BRUTO,
       1 AS QTD,
       CAST(COALESCE(D2_PRUNIT, 0) AS DECIMAL(16, 4)) AS VL_UNITARIO,
       CAST(COALESCE(D2_SEGURO, 0) AS DECIMAL(14, 2)) AS VL_SEGURO
FROM SD2010 SD2
    INNER JOIN SF2010 SF2
        ON F2_FILIAL = D2_FILIAL
        AND F2_CLIENTE = D2_CLIENTE
        AND F2_LOJA = D2_LOJA
        AND F2_DOC = D2_DOC
        AND F2_SERIE = D2_SERIE
        AND SF2.D_E_L_E_T_= ' '
    INNER JOIN SB1010 SB1
        ON B1_FILIAL = '      '
        AND SB1.B1_COD = SD2.D2_COD
        AND SB1.D_E_L_E_T_= ' '
    INNER JOIN SF4010 SF4
        ON F4_FILIAL = '      '
        AND SF4.F4_CODIGO = SD2.D2_TES
        AND SF4.D_E_L_E_T_ = ' '
    LEFT JOIN SA1010 SA1
        ON A1_FILIAL = '      '
        AND SA1.A1_COD = SF2.F2_CLIENTE
        AND SA1.A1_LOJA = SF2.F2_LOJA
        AND SA1.D_E_L_E_T_= ' '
    LEFT JOIN SBM010 SBM
        ON BM_FILIAL = '      '
        AND BM_GRUPO = B1_GRUPO
        AND SBM.D_E_L_E_T_ = ' '
    LEFT JOIN SA3010 SA3
        ON A3_FILIAL = '      '
        AND A3_COD = F2_VEND1
        AND SA3.D_E_L_E_T_ = ' '
    LEFT JOIN CTD010 CTD
        ON CTD_FILIAL = '      '
        AND CTD_ITEM = D2_ITEMCC
        AND CTD.D_E_L_E_T_ = ' '
    LEFT JOIN SX5010 CFOP
        ON X5_FILIAL = '      '
        AND X5_TABELA = '13'
        AND X5_CHAVE = D2_CF
        AND CFOP.D_E_L_E_T_ = ' '
    LEFT JOIN SE4010 SE4
        ON E4_FILIAL = '      '
        AND E4_CODIGO = F2_COND
        AND SE4.D_E_L_E_T_ = ' '
    LEFT JOIN ACY010 ACY
        ON ACY_FILIAL = SUBSTRING(D2_FILIAL, 1, 4)
        AND ACY_GRPVEN = A1_GRPVEN
        AND ACY.D_E_L_E_T_ = ' '
    LEFT JOIN SAH010 SAH
        ON AH_FILIAL = '      '
        AND AH_UNIMED = D2_UM
        AND SAH.D_E_L_E_T_ = ' '
WHERE
        D2_EMISSAO BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
    AND D2_TIPO NOT IN ('B', 'D')
    AND SD2.D_E_L_E_T_ = ' '
    AND SD2.D2_SERIE NOT IN ('003', '100')