select
    'P |01|01' as BK_EMPRESA,
    case when E2_FILIAL is null then 'P |01||' else 'P |01|01'+ CAST(E2_FILIAL as CHAR (6)) end as BK_FILIAL,
    'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DOCESP.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(E2_TIPO, ' ')), ' '), '|') as BK_ESPEC_DOC,
    'P |'+'|' as BK_TPCARTEIRA,
    'P |01|CTT010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTT_FILIAL, ' '))+'|'+RTRIM(COALESCE(E2_CCUSTO, ' ')), ' '), '|') as BK_CENTRO_CUSTO,
    'P |01|SED010|'+ COALESCE(NULLIF(RTRIM(COALESCE(ED_FILIAL, ' '))+'|'+RTRIM(COALESCE(E2_NATUREZ, ' ')), ' '), '|') as BK_NAT_FINANCEIRA,
    'P |01|SA2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A2_FILIAL, ' '))+'|'+RTRIM(COALESCE(E2_FORNECE, ' '))+RTRIM(COALESCE(E2_LOJA, ' ')), ' '), '|') as BK_FORNECEDOR,
    case when E2_FILORIG is null then 'P |01||' else 'P |01|01'+ CAST(E2_FILORIG as CHAR (6)) end as BK_FILIAL_ORIGEM,
    case when A2_COD_MUN = ' ' then 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A2_EST, ' ')), ' '), '|') else 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A2_EST, ' '))+RTRIM(COALESCE(A2_COD_MUN, ' ')), ' '), '|') end as BK_REGIAO,
    'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(GRPFORN.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(A2_GRUPO, ' ')), ' '), '|') as BK_GRUPO_FORNECEDOR,
    'P |01|SA6010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A6_FILIAL, ' '))+'|'+RTRIM(COALESCE(A6_COD, ' '))+RTRIM(COALESCE(A6_AGENCIA, ' '))+RTRIM(COALESCE(A6_NUMCON, ' ')), ' '), '|') as BK_BCO,
    E2_EMISSAO as DATA_DE_EMISSAO,
    E2_BAIXA as DATA_DA_BAIXA_DO_TITULO,
    E2_MOVIMEN as DATA_DA_MOVIMENTACAO,
    E2_VENCREA as VENCIMENTO_REAL,
    E2_NUM as NUMERO_TITULO,
    E2_PARCELA as NUMERO_DA_PARCELA,
    E2_NUMBOR as NUMERO_DO_BORDERO,
    E2_LOJA as LOJA,
    A2_TIPO as TIPO_DE_FORNECEDOR,
    E2_PREFIXO as PREFIXO_TITULO,
    E2_SEQBX as SEQUENCIA_DA_BAIXA,
    E2_VALOR as VALOR_DA_MOVIMENTACAO,
    E2_SALDO as VALOR_VENCIMENTO,
    E2_DESCONT as VALOR_DO_DESCONTO,
    E2_JUROS as VALOR_DO_JUROS,
    E2_MULTA as VALOR_DA_MULTA,
    E2_ACRESC as VALOR_ACRESCIMO,
    E2_DECRESC as VALOR_DECRESCIMO,
    E2_DATALIB as DATA_DA_DISPONIBILIDADE
from SE2010 SE2
    left join SA2010 SA2 on A2_FILIAL = '      '
        and A2_COD = E2_FORNECE
        and A2_LOJA = E2_LOJA
        and SA2.D_E_L_E_T_ = ' '
    left join SA6010 SA6 on A6_FILIAL = SUBSTRING(E2_FILIAL, 1, 2)
        and SA6.A6_COD = E2_BCOPAG
        and SA6.A6_AGENCIA = E2_FORAGE
        and SA6.A6_NUMCON = E2_FORCTA
        and SA6.D_E_L_E_T_ = ' '
    left join SX5010 DOCESP on DOCESP.X5_FILIAL = '      '
        and DOCESP.X5_TABELA = '05'
        and DOCESP.X5_CHAVE = E2_TIPO
        and DOCESP.D_E_L_E_T_ = ' '
    left join CTT010 CTT on CTT_FILIAL = SUBSTRING(E2_FILIAL, 1, 4)
        and CTT_CUSTO = E2_CCUSTO
        and CTT.D_E_L_E_T_ = ' '
    left join SED010 SED on ED_FILIAL = '      '
        and ED_CODIGO = E2_NATUREZ
        and SED.D_E_L_E_T_ = ' '
    left join SX5010 GRPFORN on GRPFORN.X5_FILIAL = '      '
        and GRPFORN.X5_TABELA = 'Y7'
        and GRPFORN.X5_CHAVE = A2_GRUPO
        and GRPFORN.D_E_L_E_T_ = ' '
where
        SE2.E2_EMISSAO between <<START_DATE>> and <<FINAL_DATE>>
    and SE2.D_E_L_E_T_ = ' '
