SELECT 'P |01|01' AS BK_EMPRESA,
       CASE
           WHEN C5_FILIAL IS NULL THEN 'P |01||'
           ELSE 'P |01|01'+ CAST(C5_FILIAL AS CHAR (6))
       END AS BK_FILIAL,
       'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(C5_CLIENTE, ' '))+RTRIM(COALESCE(C5_LOJACLI, ' ')), ' '), '|') AS BK_CLIENTE,
       'P |01|SA4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A4_FILIAL, ' '))+'|'+RTRIM(COALESCE(C5_TRANSP, ' ')), ' '), '|') AS BK_TRANSPORTADORA,
       'P |01|SA3010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A3_FILIAL, ' '))+'|'+RTRIM(COALESCE(C5_VEND1, ' ')), ' '), '|') AS BK_VENDEDOR,
       'P |01|SE4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(E4_FILIAL, ' '))+'|'+RTRIM(COALESCE(C5_CONDPAG, ' ')), ' '), '|') AS BK_CONDICAO_DE_PAGAMENTO,
       'P |01|SB1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(B1_FILIAL, ' '))+'|'+RTRIM(COALESCE(C6_PRODUTO, ' ')), ' '), '|') AS BK_ITEM,
       'P |01|SF4010|'+ COALESCE(NULLIF(RTRIM(COALESCE(F4_FILIAL, ' '))+'|'+RTRIM(COALESCE(C6_TES, ' ')), ' '), '|') AS BK_TES,
       CASE
           WHEN A1_COD_MUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' ')), ' '), '|')
           ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' '))+RTRIM(COALESCE(A1_COD_MUN, ' ')), ' '), '|')
       END AS BK_REGIAO,
       C5_NUM AS NUMERO_DO_PEDIDO,
       C5_EMISSAO AS DATA_DA_VENDA,
       C6_ENTREG AS DATA_DA_ENTREGA,
       C6_ITEM AS NUMERO_DO_ITEM,
       C6_VALOR AS VL_VENDA_TOTAL,
       C6_QTDVEN AS QTDE_VENDIDA,
       C6_PRCVEN AS VL_PRECO_UNITARIO,
       C6_VALOR AS VL_VENDA_MERCADORIA,
       C6_VALOR AS VL_VENDA_LIQUIDA,
       C6_PRUNIT AS VL_PRECO_LISTA,
       CASE
           WHEN C9_BLEST = ' '
                AND C9_BLCRED = '  ' THEN 'Liberado'
           ELSE 'Bloqueado'
       END STATUS_DO_ITEM_DO_PEDIDO,
       CASE
           WHEN C5_LIBEROK = '  '
                AND C5_NOTA = '  '
                AND C5_BLQ = '  ' THEN 'Aberto'
           WHEN C5_NOTA <> '  '
                OR C5_LIBEROK = 'E'
                AND C5_BLQ = '  ' THEN 'Encerrado'
           WHEN (C5_LIBEROK <> '  '
                 AND C5_NOTA = '  '
                 AND C5_BLQ = '  ') THEN 'Liberado'
           WHEN (C5_BLQ = '1') THEN 'Bloqueio por Regra'
           WHEN (C5_BLQ= '2') THEN 'Bloqueio por Verba'
       END STATUS_DO_PEDIDO
FROM SC5010 SC5
INNER JOIN SC6010 SC6 ON C6_FILIAL = C5_FILIAL
AND C6_NUM = C5_NUM
AND SC6.D_E_L_E_T_ = ' '
INNER JOIN SF4010 SF4 ON F4_FILIAL = '      '
AND SC6.C6_TES = SF4.F4_CODIGO
AND SF4.D_E_L_E_T_ = ' '
LEFT JOIN SB1010 SB1 ON B1_FILIAL = '      '
AND B1_COD = C6_PRODUTO
AND SB1.D_E_L_E_T_ = ' '
LEFT JOIN SA4010 SA4 ON A4_FILIAL = '      '
AND A4_COD = C5_TRANSP
AND SA4.D_E_L_E_T_ = ' '
LEFT JOIN SA1010 SA1 ON A1_FILIAL = '      '
AND A1_COD = C5_CLIENTE
AND A1_LOJA = C5_LOJACLI
AND SA1.D_E_L_E_T_ = ' '
LEFT JOIN SA3010 SA3 ON A3_FILIAL = '      '
AND A3_COD = C5_VEND1
AND SA3.D_E_L_E_T_ = ' '
LEFT JOIN SE4010 SE4 ON E4_FILIAL = '      '
AND E4_CODIGO = C5_CONDPAG
AND SE4.D_E_L_E_T_ = ' '
LEFT JOIN
  (SELECT C9_BLEST,
          C9_BLCRED,
          C9_PEDIDO,
          C9_PRODUTO,
          C9_ITEM,
          C9_FILIAL
   FROM SC9010 SC9
   WHERE SC9.D_E_L_E_T_ = ' '
     AND C9_SEQUEN =
       (SELECT MAX(C9_SEQUEN)
        FROM SC9010 A
        WHERE A.C9_FILIAL = SC9.C9_FILIAL
          AND A.C9_PEDIDO = SC9.C9_PEDIDO
          AND A.C9_PRODUTO = SC9.C9_PRODUTO
          AND A.C9_ITEM = SC9.C9_ITEM
          AND A.D_E_L_E_T_ = ' ') ) C9 ON C9.C9_PEDIDO = C6_NUM
AND C9.C9_PRODUTO = C6_PRODUTO
AND C9.C9_ITEM = C6_ITEM
AND C9.C9_FILIAL = C5_FILIAL
WHERE C5_EMISSAO BETWEEN <<START_DATE>> AND <<FINAL_DATE>>
  AND C5_TIPO = 'N'
  AND SC5.D_E_L_E_T_ = ' '