select
    'P |01|01' as BK_EMPRESA,
    case when E1_FILIAL is null then 'P |01||' else 'P |01|01'+ CAST(E1_FILIAL as CHAR (6)) end as BK_FILIAL,
    'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(TPTIT.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(E1_TIPO, ' ')), ' '), '|') as BK_ESPEC_DOC,
    'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(E1_CLIENTE, ' '))+RTRIM(COALESCE(E1_LOJA, ' ')), ' '), '|') as BK_CLIENTE,
    'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(STTIT.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(E1_SITUACA, ' ')), ' '), '|') as BK_MODALCOBRANCA,
    'P |01|CTT010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CTT_FILIAL, ' '))+'|'+RTRIM(COALESCE(E1_CCUSTO, ' ')), ' '), '|') as BK_CENTRO_CUSTO,
    'P |01|SED010|'+ COALESCE(NULLIF(RTRIM(COALESCE(ED_FILIAL, ' '))+'|'+RTRIM(COALESCE(E1_NATUREZ, ' ')), ' '), '|') as BK_NAT_FINANCEIRA,
    'P |01|SA6010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A6_FILIAL, ' '))+'|'+RTRIM(COALESCE(E1_BCOCLI, ' '))+RTRIM(COALESCE(E1_AGECLI, ' '))+RTRIM(COALESCE(E1_CTACLI, ' ')), ' '), '|') as BK_BCO,
    case when E1_FILORIG is null then 'P |01||' else 'P |01|01'+ CAST(E1_FILORIG as CHAR (6)) end as BK_FILIAL_ORIGEM,
    case when A1_COD_MUN = ' ' then 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' ')), ' '), '|') else 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' '))+RTRIM(COALESCE(A1_COD_MUN, ' ')), ' '), '|') end as BK_REGIAO,
    'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(A1_TIPO, ' ')), ' '), '|') as BK_GRUPO_CLIENTE,
    SE1.E1_EMISSAO as DATA_DE_EMISSAO_TITULO,
    SE1.E1_VENCREA as VENCIMENTO_REAL,
    SE1.E1_PREFIXO as PREFIXO_TITULO,
    SE1.E1_NUM as NUMERO_TITULO,
    SE1.E1_PARCELA as NUMERO_DA_PARCELA,
    SE1.E1_NUMBOR as NUMERO_DO_BORDERO,
    SE1.E1_VALOR as VALOR_DA_MOVIMENTACAO,
    SE1.E1_SALDO as SALDO_RECEBER,
    SE1.E1_BAIXA as DATA_DA_BAIXA_DO_TITULO,
    SE1.E1_DESCONT as VALOR_DO_DESCONTO,
    SE1.E1_JUROS as VALOR_DO_JUROS,
    SE1.E1_MULTA as VALOR_DA_MULTA,
    SE1.E1_ACRESC as VALOR_ACRESCIMO,
    SE1.E1_DECRESC as VALOR_DECRESCIMO,
    SE1.E1_MOVIMEN as DATA_DA_DISPONIBILIDADE
from SE1010 SE1
    left join SA1010 SA1 on A1_FILIAL = '      '
        and A1_COD = E1_CLIENTE
        and A1_LOJA = E1_LOJA
        and SA1.D_E_L_E_T_ = ' '
    left join CTT010 CTT on CTT_FILIAL = SUBSTRING(E1_FILIAL, 1, 4)
        and CTT_CUSTO = E1_CCUSTO
        and CTT.D_E_L_E_T_= ' '
    left join SED010 SED on ED_FILIAL = '      '
        and ED_CODIGO = E1_NATUREZ
        and SED.D_E_L_E_T_= ' '
    left join SA6010 SA6 on A6_FILIAL = SUBSTRING(E1_FILIAL, 1, 2)
        and A6_COD = E1_BCOCLI
        and A6_AGENCIA = E1_AGECLI
        and A6_NUMCON = E1_CTACLI
        and SA6.D_E_L_E_T_= ' '
    left join SX5010 TPTIT on X5_FILIAL = '      '
        and X5_TABELA = '05'
        and X5_CHAVE = E1_TIPO
        and TPTIT.D_E_L_E_T_ = ' '
    left join SX5010 STTIT on STTIT.X5_FILIAL = '      '
        and STTIT.X5_TABELA = '07'
        and STTIT.X5_CHAVE = E1_SITUACA
        and STTIT.D_E_L_E_T_ = ' '
where
        SE1.E1_EMISSAO between <<START_DATE>> and <<FINAL_DATE>>
    and SE1.D_E_L_E_T_ = ' '
