select
	trim(ST9.T9_CODBEM) as PNEU,
	SB1.B1_COD as PRODUTO,
	ST9.T9_CCUSTO as CC,
	ST9.T9_ITEMCTA as ATIVIDADE,
    ST9.T9_LOCPAD as ARMAZEM,
	ST9.T9_SITBEM as SITUACAO,
	ST9.T9_ESTRUTU as APLICADO,
	TQS.TQS_MEDIDA,
    trim(TQT.TQT_DESMED) as MEDIDA,
	ST9.T9_STATUS as STATUS,
    trim(TQY.TQY_DESTAT) as DESC_STATUS,
    ST9.T9_CONTACU as CONT_ACUM,
	ST9.T9_VALCPA as T9_VALCPA,
	cast(ST9.T9_DTCOMPR as date) as DATA_COMPRA,
	ST9.T9_FORNECE,
	trim(SA2.A2_NOME) as RAZAO_SOCIAL,
    trim(SA2.A2_NREDUZ) as NOME_FANTASIA,

	trim(ST7.T7_NOME) as FABRICANTE,
	TQS.TQS_BANDAA as BANDA_ATUAL,
	(select TQX010.TQX_SULCOO from TQX010 where TQX010.D_E_L_E_T_ = '' and TQX010.TQX_TIPMOD = TQR.TQR_TIPMOD and TQX010.TQX_MEDIDA = TQT.TQT_MEDIDA) as SULCO_ORI,
	(select TQX010.TQX_KMESPO from TQX010 where TQX010.D_E_L_E_T_ = '' and TQX010.TQX_TIPMOD = TQR.TQR_TIPMOD and TQX010.TQX_MEDIDA = TQT.TQT_MEDIDA) as CONTADOR_ESP,
	(select TQX010.TQX_XTBAND from TQX010 where TQX010.D_E_L_E_T_ = '' and TQX010.TQX_TIPMOD = TQR.TQR_TIPMOD and TQX010.TQX_MEDIDA = TQT.TQT_MEDIDA) as BANDA_CUSTO,

	TQS.TQS_KMOR + TQS.TQS_KMR1 + TQS.TQS_KMR2 + TQS.TQS_KMR3 + TQS.TQS_KMR4 + TQS.TQS_KMR5 + TQS.TQS_KMR6 + TQS.TQS_KMR7 as kmTOT,
	
	trim(ST8.T8_NOME) as MOTIVO,
	STJ.TJ_ORDEM as OS,
	STJ.TJ_POSCONT as CONT_OS,
	STJ.TJ_SERVICO as SERVICO,
	case TR4.TR4_NUMANA when null then 0 else 1 end as qtd_ANALISE,
	cast(STJ.TJ_DTMRFIM as date) as DATA_SERVICO,
    cast(TR4.TR4_DTANAL as date) as DATA_ANALISE,
	(select trim(SX5010.X5_DESCRI) from SX5010 where SX5010.D_E_L_E_T_ = '' and SX5010.X5_TABELA = 'DP' and cast(SX5010.X5_CHAVE as int) = TR4.TR4_DESTIN) as DESTINO,
	trim(TR4.TR4_PAREC) as PARECER

from TQS010 TQS (nolock)
	inner join ST9010 ST9
		on ST9.D_E_L_E_T_ = ''
		and ST9.T9_CODBEM = TQS.TQS_CODBEM

		left join TQY010 TQY
			on TQY.D_E_L_E_T_ = ''
			and TQY.TQY_STATUS = ST9.T9_STATUS
		left join SA2010 SA2
			on SA2.D_E_L_E_T_ = ''
			and SA2.A2_COD + SA2.A2_LOJA = ST9.T9_FORNECE + ST9.T9_LOJA
		
		left join TQR010 TQR
			on TQR.D_E_L_E_T_ = ''
			and TQR.TQR_TIPMOD = ST9.T9_TIPMOD

			left join ST7010 ST7
				on ST7.D_E_L_E_T_ = ''
				and ST7.T7_FABRICA = TQR.TQR_FABRIC
			
	left join TQT010 TQT
		on TQT.D_E_L_E_T_ = ''
		and TQT.TQT_MEDIDA = TQS.TQS_MEDIDA
		
		left join SB1010 SB1
			on SB1.D_E_L_E_T_ = ''
			and SB1.B1_XMEDIDA = TQT.TQT_MEDIDA

	inner join TR4010 TR4 (nolock)
		on TR4.D_E_L_E_T_ = ''
		and TR4.TR4_CODBEM = TQS.TQS_CODBEM
		
		left join ST8010 ST8 (nolock)
			on ST8.D_E_L_E_T_ = ''
			and ST8.T8_CODOCOR = TR4.TR4_MOTIVO
	
	left join STJ010 STJ
		on STJ.D_E_L_E_T_ = ''
		and STJ.TJ_CODBEM = TQS.TQS_CODBEM

where TQS.D_E_L_E_T_ = ''
