 SELECT T9_CODBEM AS PNEU,

       T9_CONTACU AS CONTADOR,

       VL_SERV,

       T9_VALCPA AS VL_COMPRA,

       VL_SERV+T9_VALCPA AS VALOR_PNEU,

       (VL_SERV+T9_VALCPA)/coalesce(nullif(T9_CONTACU, 0), 1) AS CPK

FROM

  (SELECT SUM(TJ_CUSTMDO+TJ_CUSTMAT+TJ_CUSTMAA+TJ_CUSTMAS+TJ_CUSTTER+TJ_CUSTFER) AS VL_SERV,

          TJ_CODBEM

   FROM STJ010 STJ

   WHERE STJ.D_E_L_E_T_ <> '*'

     AND TJ_TERMINO = 'S'

     AND TJ_SITUACA = 'L'

   GROUP BY TJ_CODBEM)P

JOIN ST9010 ST9 ON (T9_CODBEM = TJ_CODBEM

                    AND T9_CATBEM = '3'

                    AND ST9.D_E_L_E_T_ = '')

ORDER BY TJ_CODBEM