select
	trim(ST9.T9_CODBEM) as PNEU,
	SB1.B1_COD as PRODUTO,
    ST9.T9_LOCPAD as ARMAZEM,
	ST9.T9_SITBEM as SITUACAO,
	TQS.TQS_MEDIDA,
    trim(TQT.TQT_DESMED) as MEDIDA,
	ST9.T9_STATUS as STATUS,
    trim(TQY.TQY_DESTAT) as DESC_STATUS,
    ST9.T9_CONTACU as CONT_ACUM,

	ST9.T9_VALCPA as T9_VALCPA,
	cast(ST9.T9_DTCOMPR as date) as DATA_COMPRA,
	ST9.T9_FORNECE,
	trim(SA2.A2_NOME) as RAZAO_SOCIAL,
    trim(SA2.A2_NREDUZ) as NOME_FANTASIA,

	ST9.T9_CCUSTO as CCUSTO,
	ST9.T9_ITEMCTA as ATIVIDADE,
	ST9.T9_ESTRUTU as APLICADO,

	TQX.TQX_SULCOO as SULCO_ORI,
	TQX.TQX_KMESPO as CONTADOR_ESP,
	TQX.TQX_XTBAND as BANDA_CUSTO,
	trim(ST7.T7_NOME) as FABRICANTE,

	TQS.TQS_KMOR,
	TQS.TQS_KMR1,
	TQS.TQS_KMR2,
	TQS.TQS_KMR3,
	TQS.TQS_KMR4,
	TQS.TQS_KMR5,
	TQS.TQS_KMR6,
	TQS.TQS_KMR7,
	TQS.TQS_KMOR + TQS.TQS_KMR1 + TQS.TQS_KMR2 + TQS.TQS_KMR3 + TQS.TQS_KMR4 + TQS.TQS_KMR5 + TQS.TQS_KMR6 + TQS.TQS_KMR7 as kmTOT

from TQS010 TQS (nolock)
	inner join ST9010 ST9
		on ST9.D_E_L_E_T_ = ''
		and ST9.T9_CODBEM = TQS.TQS_CODBEM

		left join TQY010 TQY
			on TQY.D_E_L_E_T_ = ''
			and TQY.TQY_STATUS = ST9.T9_STATUS
		left join SA2010 SA2
			on SA2.D_E_L_E_T_ = ''
			and SA2.A2_COD + SA2.A2_LOJA = ST9.T9_FORNECE + ST9.T9_LOJA
	
	left join TQT010 TQT
		on TQT.D_E_L_E_T_ = ''
		and TQT.TQT_MEDIDA = TQS.TQS_MEDIDA
	
		left join TQX010 TQX
			on TQX.D_E_L_E_T_ = ''
			and TQX.TQX_MEDIDA = TQT.TQT_MEDIDA

			left join TQR010 TQR
				on TQR.D_E_L_E_T_ = ''
				and TQR.TQR_TIPMOD = TQX.TQX_TIPMOD
			
				left join ST7010 ST7
					on ST7.D_E_L_E_T_ = ''
					and ST7.T7_FABRICA = TQR.TQR_FABRIC
		
		left join SB1010 SB1
			on SB1.D_E_L_E_T_ = ''
			and SB1.B1_XMEDIDA = TQT.TQT_MEDIDA
where
		TQS.D_E_L_E_T_ = ''
