select
	trim(STZ.TZ_ORDEM) as TZ_ORDEM,
	trim(ST9.T9_CODBEM) as COMPONETE,
	trim(STZ.TZ_BEMPAI) as ESTRUTURA,
	ST9.T9_STATUS,
	ST9.T9_CCUSTO as CCUSTO,
	ST9.T9_ITEMCTA as ATIVIDADE,
	ST9.T9_ESTRUTU as APLICADO,
	last_value(STZ.TZ_BEMPAI) over (partition by STZ.TZ_CODBEM order by STZ.TZ_CODBEM) as ESTRUTURA_ANT,

	STZ.TZ_POSCONT as CONTADOR,
	STZ.TZ_CONTSAI as CONT_SAI,
	ST9.T9_CONTACU as CONT_ACU,
	substring(STZ.TZ_DATAMOV, 1, 6) as PERIODO_ENT,
	convert(datetime, concat(STZ.TZ_DATAMOV, ' ', isnull(nullif(STZ.TZ_HORAENT, ''), '00:00')), 113) as DTENT,
    substring(STZ.TZ_DATASAI, 1, 6) as PERIODO_SAI,
	convert(datetime, concat(STZ.TZ_DATASAI, ' ', STZ.TZ_HORASAI), 113) as DTSAI,
	datediff(minute, concat(STZ.TZ_DATAMOV, ' ', STZ.TZ_HORAENT), concat(STZ.TZ_DATASAI, ' ', STZ.TZ_HORASAI))/(60*24) as TEMPO_RODADO,
	trim(STZ.TZ_TIPOMOV) as TZ_TIPOMOV,
	trim(TQT.TQT_DESMED) as MEDIDA,

	ZC5.ZC5_PNEU,
	ZC5.ZC5_VLRCOM,
	ZC5.ZC5_VLRMAN,
	ZC5.ZC5_BANDA,
	ZC5.ZC5_KMEXPE,
	ZC5.ZC5_KMRODM,
	ZC5.ZC5_ANOMES,

	ST9.T9_VALCPA as T9_VALCPA,
	convert(date, ST9.T9_DTCOMPR, 103) as T9_DTCOMPR,
	ST9.T9_SITBEM,
	ST9.T9_FORNECE,

	trim(SA2.A2_NOME) as RAZAO_SOCIAL,
    trim(SA2.A2_NREDUZ) as NOME_FANTASIA,

	TQS.TQS_KMOR,
	TQS.TQS_KMR1,
	TQS.TQS_KMR2,
	TQS.TQS_KMR3,
	TQS.TQS_KMR4,
	TQS.TQS_KMR5,
	TQS.TQS_KMR6,
	TQS.TQS_KMR7,
	TQS.TQS_KMOR + TQS.TQS_KMR1 + TQS.TQS_KMR2 + TQS.TQS_KMR3 + TQS.TQS_KMR4 + TQS.TQS_KMR5 + TQS.TQS_KMR6 + TQS.TQS_KMR7 as kmTOT,
	case when cast(STZ.TZ_CODBEM as int) > 11140 then 'PNEU NOVO' else 'PNEU ANTIGO' end as TIPO_PNEU

from TQS010 TQS
	left join TQT010 TQT
		on TQT.D_E_L_E_T_ = ''
		and TQT.TQT_MEDIDA = TQS.TQS_MEDIDA
	left join ST9010 ST9
		on ST9.D_E_L_E_T_ = ''
		and ST9.T9_CODBEM = TQS.TQS_CODBEM
		
		left join SA2010 SA2 (nolock)
			on SA2.D_E_L_E_T_ = ''
			and SA2.A2_COD + SA2.A2_LOJA = ST9.T9_FORNECE + ST9.T9_LOJA

		left join STZ010 STZ
			on STZ.D_E_L_E_T_ = ''
			and ST9.T9_CODBEM = STZ.TZ_CODBEM
	
	left join ZC5010 ZC5 (nolock)
		on ZC5.D_E_L_E_T_ = ''
		and ZC5.ZC5_PNEU = TQS.TQS_CODBEM
where
		TQS.D_E_L_E_T_ = ''
