select
    SX6.X6_FIL,
    SX6.X6_VAR,
    SX6.X6_TIPO,
    trim(SX6.X6_DESCRIC) +' '+ trim(SX6.X6_DESC1) +' '+ trim(SX6.X6_DESC2) as X6_DESCRICAO,
    SX6.X6_PROPRI,
    SX6.X6_PYME,
    SX6.X6_CONTEUD
from SX6010 SX6 (nolock)
where
        SX6.D_E_L_E_T_ = ''
    and SX6.X6_VAR in ('MV_NGSTAEU', 'MV_NGMNTES', 'MV_NGPNEST', 'MV_NG1ANAT', 'MV_NGSTAGR', 'MV_NGSTAGC', 'MV_NGSTAAT', 'MV_ULMES', 'MV_NGSTARS', 'MV_NGSTAER', 'MV_NGSTAEN', 'MV_NGSTAPL', 'MV_ESTNEG', 'MV_NGSTEST', 'MV_LOCALIZ', 'MV_NGSEREF', 'MV_NGSECON', 'MV_NGSTATR')
