SELECT 'P |01|01' AS BK_EMPRESA,
       CASE
           WHEN DUA_FILIAL IS NULL THEN 'P |01||'
           ELSE 'P |01|01'+ CAST(DUA_FILIAL AS CHAR (8))
       END AS BK_FILIAL,
       DUA_DATOCO AS DATA_OCORRENCIA,
       DUA_HOROCO AS HORA_OCORRENCIA,
       CASE
           WHEN DUA_FILOCO IS NULL THEN 'P |01||'
           ELSE 'P |01|01'+ CAST(DUA_FILOCO AS CHAR (8))
       END AS FILIAL_OCORRENCIA,
       DUA_NUMOCO AS NUMERO_OCORRENCIA,
       DUA_VIAGEM AS NUMERO_VIAGEM,
       DUA_SEQOCO AS SEQUENCIA_OCORRENCIA,
       DUA_CODOCO AS CODIGO_OCORRENCA,
       'P |01|DT2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DT2.DT2_FILIAL, ' '))+'|'+RTRIM(COALESCE(DT2_TIPOCO, ' ')), ' '), '|') AS TIPO_OCORRENCA,
       'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(REM.A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(DT6_CLIREM, ' '))+RTRIM(COALESCE(DT6_LOJREM, ' ')), ' '), '|') AS BK_REMETENTE,
       'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DES.A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(DT6_CLIDES, ' '))+RTRIM(COALESCE(DT6_LOJDES, ' ')), ' '), '|') AS BK_DESTINATARIO,
       'P |01|SA1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DEV.A1_FILIAL, ' '))+'|'+RTRIM(COALESCE(DT6_CLIDEV, ' '))+RTRIM(COALESCE(DT6_LOJDEV, ' ')), ' '), '|') AS BK_DEVEDOR,
       'P |01|DUY010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DUYORI.DUY_FILIAL, ' '))+'|'+RTRIM(COALESCE(DT6_CDRORI, ' ')), ' '), '|') AS BK_CDRORI,
       'P |01|DUY010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DUYDES.DUY_FILIAL, ' '))+'|'+RTRIM(COALESCE(DT6_CDRDES, ' ')), ' '), '|') AS BK_CDRDES,
       'P |01|DDB010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DDB_FILIAL, ' '))+'|'+RTRIM(COALESCE(DDB_CODNEG, ' ')), ' '), '|') AS BK_CODNEG,
       'P |01|SX5010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SX5.X5_FILIAL, ' '))+'|'+RTRIM(COALESCE(DT6_SERVIC, ' ')), ' '), '|') AS BK_SERNEG,
       CASE
           WHEN DT6_FILORI IS NULL THEN 'P |01||'
           ELSE 'P |01|01'+ CAST(DT6_FILORI AS CHAR (8))
       END AS BK_FILIAL_ORIGEM,
       CASE
           WHEN DT6_FILDES IS NULL THEN 'P |01||'
           ELSE 'P |01|01'+ CAST(DT6_FILDES AS CHAR (8))
       END AS BK_FILIAL_DESTINO,
       'P |'+ COALESCE(NULLIF(RTRIM(COALESCE(DT6_DOCTMS, ' ')), ' '), '|') AS BK_DOCTMS,
       'P |'+ COALESCE(NULLIF(RTRIM(COALESCE(DT6_TIPTRA, ' ')), ' '), '|') AS BK_TIPTRA,
       'P |'+ COALESCE(NULLIF(RTRIM(COALESCE(DT6_SERTMS, ' ')), ' '), '|') AS BK_SERTMS,
       CASE
           WHEN REM.A1_COD_MUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(REM.A1_EST, ' ')), ' '), '|')
           ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(REM.A1_EST, ' '))+RTRIM(COALESCE(REM.A1_COD_MUN, ' ')), ' '), '|')
       END AS BK_REGIAO_REM,
       CASE
           WHEN DES.A1_COD_MUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DES.A1_EST, ' ')), ' '), '|')
           ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DES.A1_EST, ' '))+RTRIM(COALESCE(DES.A1_COD_MUN, ' ')), ' '), '|')
       END AS BK_REGIAO_DES,
       CASE
           WHEN DEV.A1_COD_MUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DEV.A1_EST, ' ')), ' '), '|')
           ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DEV.A1_EST, ' '))+RTRIM(COALESCE(DEV.A1_COD_MUN, ' ')), ' '), '|')
       END AS BK_REGIAO_DEV,
       CASE
           WHEN DUYCAL.DUY_CODMUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DUYCAL.DUY_EST, ' ')), ' '), '|')
           ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DUYCAL.DUY_EST, ' '))+RTRIM(COALESCE(DUYCAL.DUY_CODMUN, ' ')), ' '), '|')
       END AS BK_REGIAO_CDRCAL,
       CASE
           WHEN DUYORI.DUY_CODMUN = ' ' THEN 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DUYORI.DUY_EST, ' ')), ' '), '|')
           ELSE 'P |01|CC2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(DUYORI.DUY_EST, ' '))+RTRIM(COALESCE(DUYORI.DUY_CODMUN, ' ')), ' '), '|')
       END AS BK_REGIAO_CDRORI,
       DUA_FILDOC AS FILIAL_DOCUMENTO,
       DUA_DOC AS DOCUMENTO,
       DUA_SERIE AS SERIE
FROM DUA010 DUA
    INNER JOIN DT2010 DT2
        ON DT2.DT2_FILIAL = DUA_FILIAL
        AND DT2.DT2_CODOCO = DUA.DUA_CODOCO
        AND DT2.D_E_L_E_T_ = ' '
    LEFT JOIN DT6010 DT6
        ON DUA.DUA_FILIAL = DUA_FILIAL
        AND DUA.DUA_FILDOC = DT6.DT6_FILDOC
        AND DUA.DUA_DOC = DT6.DT6_DOC
        AND DUA.DUA_SERIE = DT6.DT6_SERIE
        AND DUA.DUA_SERIE <> 'COL'
        AND DUA.DUA_SERIE <> 'PED'
        AND DUA.D_E_L_E_T_ = ' '
    
        LEFT JOIN SA1010 REM
            ON REM.A1_FILIAL = '      '
            AND REM.A1_COD = DT6.DT6_CLIREM
            AND REM.A1_LOJA = DT6.DT6_LOJREM
            AND REM.D_E_L_E_T_ = ' '
        LEFT JOIN SA1010 DES
            ON DES.A1_FILIAL = '      '
            AND DES.A1_COD = DT6.DT6_CLIDES
            AND DES.A1_LOJA = DT6.DT6_LOJDES
            AND DES.D_E_L_E_T_ = ' '
        LEFT JOIN SA1010 DEV
            ON DEV.A1_FILIAL = '      '
            AND DEV.A1_COD = DT6.DT6_CLIDEV
            AND DEV.A1_LOJA = DT6.DT6_LOJDEV
            AND DEV.D_E_L_E_T_ = ' '
        LEFT JOIN DUY010 DUYORI
            ON DUYORI.DUY_FILIAL = DT6_FILIAL
            AND DUYORI.DUY_GRPVEN = DT6.DT6_CDRORI
            AND DUYORI.D_E_L_E_T_ = ' '
        LEFT JOIN DUY010 DUYDES
            ON DUYDES.DUY_FILIAL = DT6_FILIAL
            AND DUYDES.DUY_GRPVEN = DT6.DT6_CDRDES
            AND DUYDES.D_E_L_E_T_ = ' '
        LEFT JOIN DUY010 DUYCAL
            ON DUYCAL.DUY_FILIAL = DT6_FILIAL
            AND DUYCAL.DUY_GRPVEN = DT6.DT6_CDRDES
            AND DUYCAL.D_E_L_E_T_ = ' '
        LEFT JOIN DDB010 DDB
            ON DDB.DDB_FILIAL = DT6_FILIAL
            AND DDB.DDB_CODNEG = DT6.DT6_CODNEG
            AND DDB.D_E_L_E_T_ = ' '
        LEFT JOIN SX5010 SX5
            ON SX5.X5_FILIAL = '      ' /*SUBSTRING(DT6_FILIAL, 1, 5) + SUBSTRING(X5_FILIAL, 6, 8)*/
            AND SX5.X5_TABELA = 'L4'
            AND SX5.X5_CHAVE = DT6.DT6_SERVIC
            AND SX5.D_E_L_E_T_ = ' '
WHERE
        DUA.D_E_L_E_T_ = ' '
