select
    SA2.A2_CGC as CNPJ,
    SA2.A2_NOME as RAZAO_SOCIAL,
    SA2.A2_NREDUZ as NOME_FANTASIA,
    SA2.A2_CONTATO as PESSOA_CONTATO,
    SA2.A2_TEL as CONTATO,
    SA2.A2_EMAIL as EMAIL,
    SA2.A2_END as ENDERECO,
    SA2.A2_NR_END as NUMERO_ENDERECO,
    SA2.A2_BAIRRO as BAIRRO,
    SA2.A2_MUN as MUNICIPIO,
    SA2.A2_EST as UF,
    SA2.A2_CEP as CEP,
    SA2.A2_INSCR as INSCRICAO_ESTADUAL,
    SA2.A2_INSCMU as INSCRICAO_MUNICIPAL,
    SA2.A2_COD as CODIGO,
    SA2.A2_LOJA as LOJA
from SA2010 SA2
where
        SA2.D_E_L_E_T_ = ''
