SELECT -- DADOS DA SA
 CP_FILIAL,
 CP_NUM,
 CP_ITEM,
 CP_PRODUTO,
 CP_DESCRI,
 CP_CODSOLI,
 CP_USER,
 CP_SOLICIT,
 CP_EMISSAO,
 CP_YHORASA,
 CP_YHORAPR,
 CP_YDATAPR,
 CP_YHORABA,
 CP_YDATABA, -- ALCADA DA SA
 DBMSA.DBM_ITEMRA,
 DBMSA.DBM_USER,
 SCRSA.CR_NIVEL,
 SCRSA.CR_STATUS,
 CASE
     WHEN SCRSA.CR_STATUS = '01' THEN 'Aguardando nivel anterior'
     WHEN SCRSA.CR_STATUS = '02' THEN 'Pendente'
     WHEN SCRSA.CR_STATUS = '03' THEN 'Liberado'
     WHEN SCRSA.CR_STATUS = '04' THEN 'Bloqueado'
     WHEN SCRSA.CR_STATUS = '05' THEN 'Liberado outro aprov.'
     WHEN SCRSA.CR_STATUS = '06' THEN 'Rejeitado'
     WHEN SCRSA.CR_STATUS = '07' THEN 'Rej/Bloq outro aprov.'
 END AS SCRSA_STATUS,
 SCRSA.CR_DATALIB,
 SCRSA.CR_YHRLIB, -- DADOS DA SC
 C1_FILIAL,
 C1_NUM,
 C1_ITEM,
 C1_FILENT,
 C1_PRODUTO,
 C1_DESCRI,
 C1_USER,
 C1_SOLICIT,
 C1_COTACAO,
 C1_PEDIDO,
 C1_ITEMPED,
 C1_EMISSAO,
 C1_YHORASC, -- ALCADA DA SC
 DBMSC.DBM_ITEMRA,
 DBMSC.DBM_USER,
 SCRSC.CR_NIVEL,
 SCRSC.CR_STATUS,
 CASE
     WHEN SCRSC.CR_STATUS = '01' THEN 'Aguardando nivel anterior'
     WHEN SCRSC.CR_STATUS = '02' THEN 'Pendente'
     WHEN SCRSC.CR_STATUS = '03' THEN 'Liberado'
     WHEN SCRSC.CR_STATUS = '04' THEN 'Bloqueado'
     WHEN SCRSC.CR_STATUS = '05' THEN 'Liberado outro aprov.'
     WHEN SCRSC.CR_STATUS = '06' THEN 'Rejeitado'
     WHEN SCRSC.CR_STATUS = '07' THEN 'Rej/Bloq outro aprov.'
 END AS SCRSC_STATUS,
 SCRSC.CR_DATALIB,
 SCRSC.CR_YHRLIB, -- DADOS DA COTACAO
 DHU_FILIAL,
 DHU_NUM,
 DHU_DTEMIS,
 DHU_DTEMIS,
 DHU_YHORAC,
 DHU_CODCOM,
 C8_NUMSC,
 C8_ITEMSC,
 C8_ITEM,
 C8_FORNECE,
 C8_LOJA,
 C8_FILIAL,
 C8_NUM,
 C8_FILENT,
 C8_YDTFOR,
 C8_YHRFOR,
 C8_PRODUTO,
 C8_NUMPED,
 C8_ITEMPED, -- DADOS DO PEDIDO DE COMPRA
 C7_NUMCOT,
 C7_NUMSC,
 C7_ITEMSC,
 C7_FORNECE,
 C7_LOJA,
 C7_FILIAL,
 C7_NUM,
 C7_ITEM,
 C7_FILENT,
 C7_PRODUTO,
 C7_DESCRI,
 C7_USER,
 C7_EMISSAO,
 C7_YHORAPC, -- ALCADA DO PEDIDO DE COMPRA
 SCRPC.CR_USER,
 SCRPC.CR_NIVEL,
 SCRPC.CR_STATUS,
 CASE
     WHEN SCRPC.CR_STATUS = '01' THEN 'Aguardando nivel anterior'
     WHEN SCRPC.CR_STATUS = '02' THEN 'Pendente'
     WHEN SCRPC.CR_STATUS = '03' THEN 'Liberado'
     WHEN SCRPC.CR_STATUS = '04' THEN 'Bloqueado'
     WHEN SCRPC.CR_STATUS = '05' THEN 'Liberado outro aprov.'
     WHEN SCRPC.CR_STATUS = '06' THEN 'Rejeitado'
     WHEN SCRPC.CR_STATUS = '07' THEN 'Rej/Bloq outro aprov.'
 END AS SCRPC_STATUS,
 SCRPC.CR_DATALIB, -- DADOS DO DOCUMENTO DE ENTRADA
 D1_PEDIDO,
 D1_ITEMPC,
 D1_FORNECE,
 D1_LOJA,
 D1_FILIAL,
 D1_DOC,
 D1_SERIE,
 D1_EMISSAO,
 F1_YHORANF,
 D1_COD
FROM SCP010 SCP
LEFT JOIN DBM010 DBMSA ON DBMSA.D_E_L_E_T_ = ''
AND DBMSA.DBM_TIPO = 'SA'
AND DBMSA.DBM_FILIAL = CP_FILIAL
AND DBMSA.DBM_NUM = CP_NUM
AND DBMSA.DBM_ITEM = CP_ITEM
LEFT JOIN SCR010 SCRSA ON SCRSA.D_E_L_E_T_ = ''
AND SCRSA.CR_TIPO = DBMSA.DBM_TIPO
AND SCRSA.CR_FILIAL = CP_FILIAL
AND SCRSA.CR_NUM = CP_NUM
AND SCRSA.CR_GRUPO = DBMSA.DBM_GRUPO
AND SCRSA.CR_ITGRP = DBMSA.DBM_ITGRP
AND SCRSA.CR_USER = DBMSA.DBM_USER
LEFT JOIN SCQ010 SCQ ON SCQ.D_E_L_E_T_ = ''
AND CQ_FILIAL = CP_FILIAL
AND CQ_NUM = CP_NUM
AND CQ_NUMSQ = CP_ITEM
FULL JOIN SC1010 SC1 ON SC1.D_E_L_E_T_ = ''
AND CQ_FILIAL= C1_FILIAL
AND CQ_NUMSC = C1_NUM
AND C1_ITEM = CQ_ITSC
LEFT JOIN DBM010 DBMSC ON DBMSC.D_E_L_E_T_ = ''
AND DBMSC.DBM_TIPO = 'SC'
AND DBMSC.DBM_FILIAL = C1_FILIAL
AND DBMSC.DBM_NUM = C1_NUM
AND DBMSC.DBM_ITEM = C1_ITEM
LEFT JOIN SCR010 SCRSC ON SCRSC.D_E_L_E_T_ = ''
AND SCRSC.CR_TIPO = DBMSC.DBM_TIPO
AND SCRSC.CR_FILIAL = C1_FILIAL
AND SCRSC.CR_NUM = C1_NUM
AND SCRSC.CR_GRUPO = DBMSC.DBM_GRUPO
AND SCRSC.CR_ITGRP = DBMSC.DBM_ITGRP
AND SCRSC.CR_USER = DBMSC.DBM_USER
LEFT JOIN DHU010 DHU ON DHU.D_E_L_E_T_ = ''
AND DHU_FILIAL = C1_FILIAL
AND DHU_NUM = C1_COTACAO
LEFT JOIN SC8010 SC8 ON SC8.D_E_L_E_T_ = ''
AND C8_FILIAL = C1_FILIAL
AND C8_NUM = C1_COTACAO
AND C8_ITEMSC = C1_ITEM
AND C8_NUMSC = C1_NUM
FULL JOIN SC7010 SC7 ON SC7.D_E_L_E_T_ = ''
AND C7_FILIAL = C1_FILIAL
AND C7_NUMSC = C1_NUM
AND C7_ITEMSC = C1_ITEM
LEFT JOIN SCR010 SCRPC ON SCRPC.D_E_L_E_T_ = ''
AND SCRPC.CR_TIPO = 'PC'
AND SCRPC.CR_FILIAL = C7_FILIAL
AND SCRPC.CR_NUM = C7_NUM
FULL JOIN SD1010 SD1 ON SD1.D_E_L_E_T_ = ''
AND D1_FILIAL = C7_FILIAL
AND D1_PEDIDO = C7_NUM
AND D1_ITEMPC = C7_ITEM
AND D1_FORNECE = C7_FORNECE
AND D1_LOJA = C7_LOJA
LEFT JOIN SF1010 SF1 ON SF1.D_E_L_E_T_ = ''
AND F1_FILIAL = D1_FILIAL
AND F1_FORNECE = D1_FORNECE
AND F1_LOJA = D1_LOJA
AND F1_DOC = D1_DOC
AND F1_SERIE = D1_SERIE
WHERE SCP.D_E_L_E_T_= ''
        OR SC1.D_E_L_E_T_ = ''
        OR SC7.D_E_L_E_T_ = ''
        OR SC8.D_E_L_E_T_ = ''
        OR SD1.D_E_L_E_T_= ''
ORDER BY SCP.CP_FILIAL,
         SCP.CP_NUM,
         SCP.CP_ITEM,
         SC1.C1_FILIAL,
         SC1.C1_NUM,
         SC1.C1_ITEM,
         DHU.DHU_FILIAL,
         DHU.DHU_NUM,
         SC8.C8_ITEM,
         SC7.C7_FILIAL,
         SC7.C7_NUM,
         SC7.C7_ITEM,
         SD1.D1_FILIAL
         