select
    SF2.F2_FILIAL as FILIAL,
    SF2.F2_SERIE as SERIE,
    SF2.F2_DOC as DOCUMENTO,
    SD2.D2_PEDIDO as PEDIDO,
    SD2.D2_ITEM as DOC_ITEM,
    convert(date, SF2.F2_EMISSAO, 103) as EMISSAO,
    convert(date, SF2.F2_EMINFE, 103) as DOC_SAIDA,
    SF2.F2_TPFRETE as TIPO_FRETE,
    SD2.D2_TIPO as DOC_TIPO,
    SD2.D2_ORIGLAN as ORIGEM_LANC,
    trim(SF3.F3_DESCRET) as MSG_NFE,
    trim(SF3.F3_OBSERV) as OBS,
    convert(date, SF3.F3_DTCANC, 103) as DATA_CANCELAMENTO,
    trim(SD2.D2_COD) as PRODUTO,
    trim(SB1.B1_DESC) as DESC_PRODUTO,
    trim(SB1.B1_GRUPO) as GRUPO_PRODUTO,
    trim(SBM.BM_DESC) as DESC_GRUPOPROD,
    trim(SD2.D2_TES) as TES,
    trim(SF4.F4_TEXTO) as DESC_TES,
    trim(SD2.D2_CF) as CFOP,
    trim(CFOP.X5_DESCRI) as DESC_CFOP,
    trim(SA1.A1_TIPO) as TIPO_CLIENTE,
    trim(SF2.F2_CLIENTE) as BK_CLIENTE,
    trim(SA1.A1_NOME) as CLIENTE,
    SF2.F2_VALBRUT as VALOR_BRUTO,
    CAST(COALESCE(SD2.D2_VALBRUT, 0) as DECIMAL(14, 2)) as VL_FATURAMENTO_TOTAL,
    CAST(COALESCE(SD2.D2_VALICM, 0) as DECIMAL(14, 2)) as VL_ICMS_FATURAMENTO,
    CAST(COALESCE(SD2.D2_VALIPI, 0) as DECIMAL(14, 2)) as VL_IPI_FATURAMENTO,
    CAST(COALESCE(SD2.D2_VALFRE, 0) as DECIMAL(14, 2)) as VL_FRETE_NF,
    CAST(COALESCE(SD2.D2_DESPESA, 0) as DECIMAL(14, 2)) as VL_DESPESA,
    CAST(COALESCE(SD2.D2_TOTAL, 0) as DECIMAL(14, 2)) as VL_FATURAMENTO_MERCADORIA,
    CAST(COALESCE(SD2.D2_VALIMP6, 0) as DECIMAL(14, 2)) as VL_PIS_FATURAMENTO,
    CAST(COALESCE(SD2.D2_VALIMP5, 0) as DECIMAL(14, 2)) as VL_COFINS_FATURAMENTO,
    CAST(COALESCE(SD2.D2_QUANT, 0) as DECIMAL(13, 3)) as QTD_FATURADA_ITEM,
    CAST(COALESCE(SD2.D2_VALISS, 0) as DECIMAL(14, 2)) as VL_ISS_FATURAMENTO,
    CAST(COALESCE(SD2.D2_ICMSRET, 0) as DECIMAL(14, 2)) as VL_ICMS_SUBST_FATURAMENTO,
    CAST(COALESCE(SD2.D2_DESCON, 0) as DECIMAL(12, 2)) as VL_DESCONTO_FATURAMENTO,
    CAST(COALESCE(SD2.D2_VALIRRF, 0) as DECIMAL(14, 2)) as VL_IRF_FATURAMENTO,
    CAST(COALESCE(SD2.D2_VALINS, 0) as DECIMAL(14, 2)) as VL_INSS_FATURAMENTO,
    CAST(COALESCE(SD2.D2_PESO * SD2.D2_QUANT, 0) as DECIMAL(12, 4)) as PESO_LIQUIDO,
    CAST(COALESCE(SB1.B1_PESBRU * SD2.D2_QUANT, 0) as DECIMAL(12, 4)) as PESO_BRUTO,
    1 as QTD,
    CAST(COALESCE(SD2.D2_PRUNIT, 0) as DECIMAL(16, 4)) as VL_UNITARIO,
    CAST(COALESCE(SD2.D2_SEGURO, 0) as DECIMAL(14, 2)) as VL_SEGURO
from SF3010 SF3 (nolock)
    inner join SF2010 SF2 (nolock)
        on SF2.F2_SERIE not in ('003', '100')
        and SF2.F2_CLIENTE = SF3.F3_CLIEFOR
        and SF2.F2_LOJA = SF3.F3_LOJA
        and SF2.F2_DOC = SF3.F3_NFISCAL
        and SF2.F2_SERIE = SF3.F3_SERIE
    left join SD2010 SD2 (nolock)
        on SD2.D2_FILIAL = SF2.F2_FILIAL
        and SD2.D2_CLIENTE = SF2.F2_CLIENTE
        and SD2.D2_LOJA = SF2.F2_LOJA
        and SD2.D2_DOC = SF2.F2_DOC
        and SD2.D2_SERIE = SF2.F2_SERIE
        and SD2.D2_TIPO not in ('B', 'D')
    left join SB1010 SB1 (nolock)
        and SB1.B1_COD = SD2.D2_COD
        and SB1.D_E_L_E_T_= ' '
    left join SF4010 SF4 (nolock)
        and SF4.F4_CODIGO = SD2.D2_TES
        and SF4.D_E_L_E_T_ = ' '
    left join SX5010 CFOP (nolock)
        and X5_TABELA = '13'
        and X5_CHAVE = D2_CF
        and CFOP.D_E_L_E_T_ = ' '
    left join SA1010 SA1 (nolock)
        and SA1.A1_COD = SF2.F2_CLIENTE
        and SA1.A1_LOJA = SF2.F2_LOJA
        and SA1.D_E_L_E_T_= ' '
    left join SBM010 SBM (nolock)
        on BM_GRUPO = B1_GRUPO
        and SBM.D_E_L_E_T_ = ' '
where SF3.D_E_L_E_T_ = ''
