SELECT *
FROM
  (SELECT DISTINCT 'P |01|01' AS BK_EMPRESA,
                   CASE
                       WHEN CQ1_FILIAL IS NULL THEN 'P |01||'
                       ELSE 'P |01|01'+ CAST(CQ1_FILIAL AS CHAR (6))
                   END AS BK_FILIAL,
                   'P |01|CT1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(CT1_FILIAL, ' '))+'|'+RTRIM(COALESCE(CQ1_CONTA, ' ')), ' '), '|') AS BK_CONTA,
                   CT1_NORMAL AS
   NORMAL,
                   CT1_RES AS CTARES,
                   CT1_CLASSE AS TIPOCONTA,
                   CT1_GRUPO AS GRUPO,
                   CT1_NATCTA AS NATCTA,
                   CT1_DTEXSF AS CT1DTEXSF,
                   CT1_DESC01 AS DESCCTA,<<FINAL_DATE>> AS DATA,

     (SELECT CASE
                 WHEN SUM(CQ1_DEBITO) IS NULL THEN 0
                 ELSE SUM(CQ1_DEBITO)
             END AS SALDOANTDB
      FROM CQ1010 CQ11
      WHERE CQ11.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ11.CQ1_TPSALD = '1'
        AND CQ11.CQ1_DATA < <<START_DATE>>
        AND CQ11.D_E_L_E_T_ = ' '
        AND CQ11.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ11.CQ1_MOEDA = '01') AS SALDOANTDB,

     (SELECT CASE
                 WHEN SUM(CQ1_CREDIT) IS NULL THEN 0
                 ELSE SUM(CQ1_CREDIT)
             END AS SALDOANTCR
      FROM CQ1010 CQ12
      WHERE CQ12.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ12.CQ1_TPSALD = '1'
        AND CQ12.CQ1_DATA < <<START_DATE>>
        AND CQ12.D_E_L_E_T_ = ' '
        AND CQ12.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ12.CQ1_MOEDA = '01') AS SALDOANTCR,

     (SELECT CASE
                 WHEN SUM(CQ1_DEBITO) IS NULL THEN 0
                 ELSE SUM(CQ1_DEBITO)
             END AS SALDODEB
      FROM CQ1010 CQ13
      WHERE CQ13.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ13.CQ1_TPSALD = '1'
        AND CQ13.CQ1_DATA >= <<START_DATE>>
        AND CQ13.CQ1_DATA <= <<FINAL_DATE>>
        AND CQ13.D_E_L_E_T_ = ' '
        AND CQ13.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ13.CQ1_MOEDA = '01') AS SALDODEB,

     (SELECT CASE
                 WHEN SUM(CQ1_CREDIT) IS NULL THEN 0
                 ELSE SUM(CQ1_CREDIT)
             END AS SALDOCRD
      FROM CQ1010 CQ14
      WHERE CQ14.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ14.CQ1_TPSALD = '1'
        AND CQ14.CQ1_DATA >= <<START_DATE>>
        AND CQ14.CQ1_DATA <= <<FINAL_DATE>>
        AND CQ14.D_E_L_E_T_ = ' '
        AND CQ14.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ14.CQ1_MOEDA = '01') AS SALDOCRD,

     (SELECT CASE
                 WHEN SUM(CQ1_DEBITO) IS NULL THEN 0
                 ELSE SUM(CQ1_DEBITO)
             END AS SALDOANTDB
      FROM CQ1010 CQ15
      WHERE CQ15.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ15.CQ1_TPSALD = '2'
        AND CQ15.CQ1_DATA < <<START_DATE>>
        AND CQ15.D_E_L_E_T_ = ' '
        AND CQ15.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ15.CQ1_MOEDA = '01') AS SALDOANTDBP,

     (SELECT CASE
                 WHEN SUM(CQ1_CREDIT) IS NULL THEN 0
                 ELSE SUM(CQ1_CREDIT)
             END AS SALDOANTCR
      FROM CQ1010 CQ16
      WHERE CQ16.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ16.CQ1_TPSALD = '2'
        AND CQ16.CQ1_DATA < <<START_DATE>>
        AND CQ16.D_E_L_E_T_ = ' '
        AND CQ16.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ16.CQ1_MOEDA = '01') AS SALDOANTCRP,

     (SELECT CASE
                 WHEN SUM(CQ1_DEBITO) IS NULL THEN 0
                 ELSE SUM(CQ1_DEBITO)
             END AS SALDODEB
      FROM CQ1010 CQ17
      WHERE CQ17.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ17.CQ1_TPSALD = '2'
        AND CQ17.CQ1_DATA >= <<START_DATE>>
        AND CQ17.CQ1_DATA <= <<FINAL_DATE>>
        AND CQ17.D_E_L_E_T_ = ' '
        AND CQ17.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ17.CQ1_MOEDA = '01') AS SALDODEBP,

     (SELECT CASE
                 WHEN SUM(CQ1_CREDIT) IS NULL THEN 0
                 ELSE SUM(CQ1_CREDIT)
             END AS SALDOCRD
      FROM CQ1010 CQ18
      WHERE CQ18.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ18.CQ1_TPSALD = '2'
        AND CQ18.CQ1_DATA >= <<START_DATE>>
        AND CQ18.CQ1_DATA <= <<FINAL_DATE>>
        AND CQ18.D_E_L_E_T_ = ' '
        AND CQ18.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ18.CQ1_MOEDA = '01') AS SALDOCRDP,

     (SELECT CASE
                 WHEN SUM(CQ1_DEBITO) IS NULL THEN 0
                 ELSE SUM(CQ1_DEBITO)
             END AS SALDOANTDB
      FROM CQ1010 CQ19
      WHERE CQ19.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ19.CQ1_TPSALD = '4'
        AND CQ19.CQ1_DATA < <<START_DATE>>
        AND CQ19.D_E_L_E_T_ = ' '
        AND CQ19.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ19.CQ1_MOEDA = '01') AS SALDOANTDBE,

     (SELECT CASE
                 WHEN SUM(CQ1_CREDIT) IS NULL THEN 0
                 ELSE SUM(CQ1_CREDIT)
             END AS SALDOANTCR
      FROM CQ1010 CQ110
      WHERE CQ110.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ110.CQ1_TPSALD = '4'
        AND CQ110.CQ1_DATA < <<START_DATE>>
        AND CQ110.D_E_L_E_T_ = ' '
        AND CQ110.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ110.CQ1_MOEDA = '01') AS SALDOANTCRE,

     (SELECT CASE
                 WHEN SUM(CQ1_DEBITO) IS NULL THEN 0
                 ELSE SUM(CQ1_DEBITO)
             END AS SALDODEB
      FROM CQ1010 CQ111
      WHERE CQ111.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ111.CQ1_TPSALD = '4'
        AND CQ111.CQ1_DATA >= <<START_DATE>>
        AND CQ111.CQ1_DATA <= <<FINAL_DATE>>
        AND CQ111.D_E_L_E_T_ = ' '
        AND CQ111.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ111.CQ1_MOEDA = '01') AS SALDODEBE,

     (SELECT CASE
                 WHEN SUM(CQ1_CREDIT) IS NULL THEN 0
                 ELSE SUM(CQ1_CREDIT)
             END AS SALDOCRD
      FROM CQ1010 CQ112
      WHERE CQ112.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ112.CQ1_TPSALD = '4'
        AND CQ112.CQ1_DATA >= <<START_DATE>>
        AND CQ112.CQ1_DATA <= <<FINAL_DATE>>
        AND CQ112.D_E_L_E_T_ = ' '
        AND CQ112.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ112.CQ1_MOEDA = '01') AS SALDOCRDE,

     (SELECT CASE
                 WHEN SUM(CQ1_DEBITO) IS NULL THEN 0
                 ELSE SUM(CQ1_DEBITO)
             END AS SALDOANTDB
      FROM CQ1010 CQ113
      WHERE CQ113.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ113.CQ1_TPSALD = '0'
        AND CQ113.CQ1_DATA < <<START_DATE>>
        AND CQ113.D_E_L_E_T_ = ' '
        AND CQ113.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ113.CQ1_MOEDA = '01') AS SALDOANTDBO,

     (SELECT CASE
                 WHEN SUM(CQ1_CREDIT) IS NULL THEN 0
                 ELSE SUM(CQ1_CREDIT)
             END AS SALDOANTCR
      FROM CQ1010 CQ114
      WHERE CQ114.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ114.CQ1_TPSALD = '0'
        AND CQ114.CQ1_DATA < <<START_DATE>>
        AND CQ114.D_E_L_E_T_ = ' '
        AND CQ114.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ114.CQ1_MOEDA = '01') AS SALDOANTCRO,

     (SELECT CASE
                 WHEN SUM(CQ1_DEBITO) IS NULL THEN 0
                 ELSE SUM(CQ1_DEBITO)
             END AS SALDODEB
      FROM CQ1010 CQ115
      WHERE CQ115.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ115.CQ1_TPSALD = '0'
        AND CQ115.CQ1_DATA >= <<START_DATE>>
        AND CQ115.CQ1_DATA <= <<FINAL_DATE>>
        AND CQ115.D_E_L_E_T_ = ' '
        AND CQ115.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ115.CQ1_MOEDA = '01') AS SALDODEBO,

     (SELECT CASE
                 WHEN SUM(CQ1_CREDIT) IS NULL THEN 0
                 ELSE SUM(CQ1_CREDIT)
             END AS SALDOCRD
      FROM CQ1010 CQ116
      WHERE CQ116.CQ1_CONTA = CQ1.CQ1_CONTA
        AND CQ116.CQ1_TPSALD = '0'
        AND CQ116.CQ1_DATA >= <<START_DATE>>
        AND CQ116.CQ1_DATA <= <<FINAL_DATE>>
        AND CQ116.D_E_L_E_T_ = ' '
        AND CQ116.CQ1_FILIAL = CQ1.CQ1_FILIAL
        AND CQ116.CQ1_MOEDA = '01') AS SALDOCRDO
   FROM CQ1010 CQ1
   INNER JOIN CT1010 CT1 ON CT1_FILIAL = CQ1_FILIAL
   AND CT1_CONTA = CQ1_CONTA
   AND CT1.D_E_L_E_T_ = ' '
   WHERE CQ1.D_E_L_E_T_ = ' '
     AND CQ1.CQ1_MOEDA = '01' ) SALDOARQ
WHERE (SALDOANTDB - SALDOANTCR <> 0
       OR SALDODEB <> 0
       OR SALDOCRD <> 0)
  OR (SALDOANTDBO - SALDOANTCRO <> 0
      OR SALDODEBO <> 0
      OR SALDOCRDO <> 0)
  OR (SALDOANTDBE - SALDOANTCRE <> 0
      OR SALDODEBE <> 0
      OR SALDOCRDE <> 0)
  OR (SALDOANTDBP - SALDOANTCRP <> 0
      OR SALDODEBP <> 0
      OR SALDOCRDP <> 0)