SELECT
    'P |01|SAK010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SAK.AK_FILIAL, ' '))+'|'+RTRIM(COALESCE(SAK.AK_COD, ' ')), ' '), '|') AS BK_APROVADOR,
    SAK.AK_COD as COD_APROVADOR,
    SAK.AK_USER as COD_USUARIO,
    upper(trim(SAK.AK_LOGIN)) as DESC_APROVADOR
FROM SAK010 SAK
WHERE SAK.D_E_L_E_T_ = ' '
UNION
SELECT 'P |01|SAK010||',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO'
