select
    'P |01|SY1010|'+ COALESCE(NULLIF(RTRIM(COALESCE(Y1_FILIAL, ' '))+'|'+RTRIM(COALESCE(Y1_COD, ' ')), ' '), '|') as BK_COMPRADOR,
    SY1.Y1_COD as COD_COMPRADOR,
    SY1.Y1_NOME as NOME_COMPRADOR
from SY1010 SY1
where SY1.D_E_L_E_T_ = ''

union select 'P |01|SY1010||', '01 - INDEFINIDO', 'SOLICITACAO PENDENTE'
