SELECT 'P |01|SBM010|'+ COALESCE(NULLIF(RTRIM(COALESCE(BM_FILIAL, ' '))+'|'+RTRIM(COALESCE(BM_GRUPO, ' ')), ' '), '|') AS BK_GRUPO_ESTOQUE,
       SBM.BM_GRUPO AS COD_GRUPO_ESTOQUE,
       upper(SBM.BM_DESC) AS DESC_GRUPO_ESTOQUE,
       upper(SBM.BM_YDEGRUP) AS DESC_GRUPO,
       upper(SBM.BM_YDESUBG) AS DESC_SUBGRUPO
FROM SBM010 SBM
WHERE SBM.D_E_L_E_T_ = ' '
UNION
SELECT 'P |01|SBM010||',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO'