SELECT
    'P |01|SED010|'+ COALESCE(NULLIF(RTRIM(COALESCE(SED.ED_FILIAL, ' '))+'|'+RTRIM(COALESCE(SED.ED_CODIGO, ' ')), ' '), '|') AS BK_NAT_FINANCEIRA,
    SED.ED_CODIGO as COD_NAT_FINANCEIRA,
    SED.ED_DESCRIC as DESC_NAT_FINANCEIRA,
    SED.ED_PAI as PAI_NAT_FINANCEIRA
FROM SED010 SED
WHERE SED.D_E_L_E_T_ = ' '
UNION
SELECT 'P |01|SED010||',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO',
       '01 - INDEFINIDO'
