select
    'P |01|AD2010|'+ COALESCE(NULLIF(RTRIM(COALESCE(AD2.AD2_FILIAL, ' '))+'|'+RTRIM(COALESCE(AD2.AD2_NROPOR, ' '))+RTRIM(COALESCE(AD2.AD2_REVISA, ' '))+RTRIM(COALESCE(AD2.AD2_VEND, ' ')), ' '), '|') as ID_TIMEVENDAS,
    AD2.AD2_VEND as AD2_VEND
from AD2010 AD2
where AD2.D_E_L_E_T_ = ''
