SELECT 'P |01|SA3010|'+ COALESCE(NULLIF(RTRIM(COALESCE(A3_FILIAL, ' '))+'|'+RTRIM(COALESCE(A3_COD, ' ')), ' '), '|') AS BK_VENDEDOR,
       SA3.A3_COD AS COD_REPRESENTANTE,
       SA3.A3_NREDUZ AS REPRESENTANTE
FROM SA3010 SA3
WHERE SA3.D_E_L_E_T_ = ' ' and SA3.A3_TIPO = 'I'
