select
	ABASTECE.TQN_FILIAL,
	ABASTECE.TQN_FROTA,

	ABASTECE.TQN_HODOM as km_ATUAL,
	isnull(HOD_ATUAL.TQN_HODOM, 0) as km_ANTERIOR,

	ABASTECE.TQN_HODOM - HOD_ANTERIOR.TQN_HODOM as diff,

	HOD_ANTERIOR.contador as COUNT_1,
	HOD_ATUAL.contador as COUNT_2,

	ST9010.T9_TIPMOD,
	TQR010.TQR_DESMOD,
	ABASTECE.TQN_VALTOT,
	ABASTECE.TQN_CCUSTO,
	ABASTECE.TQN_LOJA,
	ABASTECE.TQN_NOTFIS,
	ABASTECE.TQN_VALUNI,
	ABASTECE.TQN_POSTO,
	ABASTECE.TQN_CODCOM,
	ABASTECE.TQN_DTABAS,
	ABASTECE.TQN_HRABAS,
	ABASTECE.TQN_QUANT,

	year(ABASTECE.TQN_DTABAS) as ANO_ABAS,
	month(ABASTECE.TQN_DTABAS) as MES_ABAS
from TQN010 as ABASTECE (nolock)
	inner join ST9010 (nolock)
		on ST9010.D_E_L_E_T_ = ''
		and ST9010.T9_CODBEM = ABASTECE.TQN_FROTA

		inner join TQR010 (nolock)
			on TQR010.D_E_L_E_T_ = ''
			and TQR010.TQR_TIPMOD = ST9010.T9_TIPMOD

	left join
	(
		select
			ENCHE.TQN_FROTA,
			min(ENCHE.TQN_HODOM) over(partition by ENCHE.TQN_FROTA order by ENCHE.TQN_HODOM)
			case when ENCHE.TQN_HODOM = (select min(TQN010.TQN_HODOM) from TQN010 (nolock) where TQN010.TQN_FROTA = ENCHE.TQN_FROTA) then 0 else ENCHE.TQN_HODOM end as TQN_HODOM,
			ENCHE.TQN_DTABAS,
			ENCHE.TQN_HRABAS,
			row_number() over
			(
				partition by
					ENCHE.TQN_FROTA
				order by
					ENCHE.TQN_FROTA,
					ENCHE.TQN_HODOM
			) as contador
		from TQN010 as ENCHE (nolock)
		where
				ENCHE.D_E_L_E_T_ = ''
	) as HOD_ANTERIOR
		on HOD_ANTERIOR.TQN_FROTA = ABASTECE.TQN_FROTA
		and HOD_ANTERIOR.TQN_DTABAS = ABASTECE.TQN_DTABAS
		and HOD_ANTERIOR.TQN_HRABAS = ABASTECE.TQN_HRABAS

		left join
		(
			select
				TQN010.TQN_FROTA,
				TQN010.TQN_HODOM,
				TQN010.TQN_DTABAS,
				TQN010.TQN_HRABAS,
				row_number() over
				(
					partition by
						TQN010.TQN_FROTA
					order by
						TQN010.TQN_FROTA,
						TQN010.TQN_HODOM
				) as contador
			from TQN010 (nolock)
			where TQN010.D_E_L_E_T_ = ''
		) as HOD_ATUAL
			on HOD_ANTERIOR.TQN_FROTA = HOD_ATUAL.TQN_FROTA
			and HOD_ANTERIOR.TQN_DTABAS = HOD_ATUAL.TQN_DTABAS
			and HOD_ANTERIOR.TQN_HRABAS = HOD_ATUAL.TQN_HRABAS
where
		ABASTECE.D_E_L_E_T_ = ''