select
	ABASTECE.TQN_FILIAL,
	ABASTECE.TQN_FROTA,
	ABASTECE.TQN_VALTOT,
	ABASTECE.TQN_CCUSTO,
	ABASTECE.TQN_LOJA,
	ABASTECE.TQN_NOTFIS,
	ABASTECE.TQN_VALUNI,
	ABASTECE.TQN_POSTO,
	ABASTECE.TQN_CODCOM,
	ABASTECE.TQN_DTABAS,
	ABASTECE.TQN_HRABAS,
	ABASTECE.TQN_QUANT,

	ST9.T9_TIPMOD,
	TQR.TQR_DESMOD,
	STP.TP_DTLEITU,
	STP.TP_HORA,
	STP.TP_ACUMCON,

	ABASTECE.TQN_HODOM,
	min(ABASTECE.TQN_HODOM) as km_MIN,
	max(ABASTECE.TQN_HODOM) as km_MAX,

	(
		select max(TQN010.TQN_HODOM)
		from TQN010 (nolock)
		where
				TQN010.TQN_FILIAL = ABASTECE.TQN_FILIAL
			and TQN010.TQN_FROTA = ABASTECE.TQN_FROTA
			and datediff(month, TQN010.TQN_DTABAS, ABASTECE.TQN_DTABAS) = 1
	) as km_ANT,

	ABASTECE.ANO_ABAS,
	ABASTECE.MES_ABAS

from
	(
		select
			case cast(TQN010.TQN_POSTO as int)
				when 59 then '010102'
				else trim(isnull(TQN010.TQN_FILIAL, '-'))
			end as TQN_FILIAL,
			TQN010.TQN_FROTA,
			TQN010.TQN_VALTOT,
			TQN010.TQN_CCUSTO,
			TQN010.TQN_LOJA,
			TQN010.TQN_NOTFIS,
			TQN010.TQN_VALUNI,
			TQN010.TQN_POSTO,
			TQN010.TQN_CODCOM,
			TQN010.TQN_DTABAS,
			TQN010.TQN_HRABAS,
			TQN010.TQN_QUANT,
			TQN010.TQN_HODOM,
			year(TQN010.TQN_DTABAS) as ANO_ABAS,
			month(TQN010.TQN_DTABAS) as MES_ABAS
		from TQN010 (nolock)
		where TQN010.D_E_L_E_T_ = ''
	) as ABASTECE

	inner join ST9010 as ST9 (nolock)
		on ST9.D_E_L_E_T_ = ''
		and ST9.T9_CODBEM = ABASTECE.TQN_FROTA

		inner join TQR010 as TQR (nolock)
			on TQR.D_E_L_E_T_ = ''
			and TQR.TQR_TIPMOD = ST9.T9_TIPMOD

	left join
	(
		select
			case cast(TQF010.TQF_CODIGO as int)
				when 59 then '010102'
				else trim(isnull(TQF010.TQF_CODFIL, '-'))
			end as TQF_FILIAL,
			TQF010.TQF_CODIGO,
			TQF010.TQF_LOJA
		from TQF010
		where TQF010.D_E_L_E_T_ = ''
	) as TQF
		on TQF.TQF_FILIAL = ABASTECE.TQN_FILIAL
		and TQF.TQF_CODIGO + TQF.TQF_LOJA = ABASTECE.TQN_POSTO + ABASTECE.TQN_LOJA
	left join STP010 as STP (nolock)
		on STP.D_E_L_E_T_ = ''
		and STP.TP_DTLEITU = ABASTECE.TQN_DTABAS
		and STP.TP_HORA = ABASTECE.TQN_HRABAS
		and STP.TP_CODBEM = ABASTECE.TQN_FROTA
group by
	ABASTECE.TQN_FILIAL,
	ABASTECE.TQN_FROTA,
	ABASTECE.TQN_VALTOT,
	ABASTECE.TQN_CCUSTO,
	ABASTECE.TQN_LOJA,
	ABASTECE.TQN_NOTFIS,
	ABASTECE.TQN_VALUNI,
	ABASTECE.TQN_POSTO,
	ABASTECE.TQN_CODCOM,
	ABASTECE.TQN_DTABAS,
	ABASTECE.TQN_HRABAS,
	ABASTECE.TQN_QUANT,
	ABASTECE.TQN_HODOM,
	ABASTECE.ANO_ABAS,
	ABASTECE.MES_ABAS,
	ST9.T9_TIPMOD,
	TQR.TQR_DESMOD,
	STP.TP_DTLEITU,
	STP.TP_HORA,
	STP.TP_ACUMCON