select
	max(COMB.diff),
	count(distinct COMB.km_ATUAL),
	COMB.TQN_FILIAL,
	COMB.TQN_FROTA,
	COMB.T9_TIPMOD,
	COMB.TQR_DESMOD,
	COMB.TQN_VALTOT,
	COMB.TQN_CCUSTO,
	COMB.TQN_LOJA,
	COMB.TQN_NOTFIS,
	COMB.TQN_VALUNI,
	COMB.TQN_POSTO,
	COMB.TQN_CODCOM,
	COMB.TQN_DTABAS,
	COMB.TQN_HRABAS,
	COMB.TQN_QUANT,
	COMB.km_ATUAL,
	COMB.km_ANTERIOR
from
(
	select
		ABASTECE.TQN_FILIAL,
		ABASTECE.TQN_FROTA,

		ABASTECE.TQN_HODOM as km_ATUAL,
		HOD_ANTERIOR.TQN_HODOM as km_ANTERIOR,

		case when (ABASTECE.TQN_HODOM - HOD_ANTERIOR.TQN_HODOM) != 0 then (ABASTECE.TQN_HODOM - HOD_ANTERIOR.TQN_HODOM) else 0 end as diff,

		ST9010.T9_TIPMOD,
		TQR010.TQR_DESMOD,
		ABASTECE.TQN_VALTOT,
		ABASTECE.TQN_CCUSTO,
		ABASTECE.TQN_LOJA,
		ABASTECE.TQN_NOTFIS,
		ABASTECE.TQN_VALUNI,
		ABASTECE.TQN_POSTO,
		ABASTECE.TQN_CODCOM,
		ABASTECE.TQN_DTABAS,
		ABASTECE.TQN_HRABAS,
		ABASTECE.TQN_QUANT,

		year(ABASTECE.TQN_DTABAS) as ANO_ABAS,
		month(ABASTECE.TQN_DTABAS) as MES_ABAS
	from TQN010 as ABASTECE (nolock)
		inner join ST9010 (nolock)
			on ST9010.D_E_L_E_T_ = ''
			and ST9010.T9_CODBEM = ABASTECE.TQN_FROTA

			inner join TQR010 (nolock)
				on TQR010.D_E_L_E_T_ = ''
				and TQR010.TQR_TIPMOD = ST9010.T9_TIPMOD

		left join
		(
			select
				ENCHE.TQN_FROTA,
				ENCHE.TQN_DTABAS,
				ENCHE.TQN_HRABAS,
				ENCHE.TQN_HODOM
			from TQN010 as ENCHE (nolock)
			where
					ENCHE.D_E_L_E_T_ = ''
		) as HOD_ANTERIOR
			on HOD_ANTERIOR.TQN_FROTA = ABASTECE.TQN_FROTA
	where
			ABASTECE.D_E_L_E_T_ = ''
) as COMB

group by
	COMB.TQN_FILIAL,
	COMB.TQN_FROTA,
	COMB.T9_TIPMOD,
	COMB.TQR_DESMOD,
	COMB.TQN_VALTOT,
	COMB.TQN_CCUSTO,
	COMB.TQN_LOJA,
	COMB.TQN_NOTFIS,
	COMB.TQN_VALUNI,
	COMB.TQN_POSTO,
	COMB.TQN_CODCOM,
	COMB.TQN_DTABAS,
	COMB.TQN_HRABAS,
	COMB.TQN_QUANT,
	COMB.km_ATUAL,
	COMB.km_ANTERIOR