select
	STJ.TJ_FILIAL as TJ_FILIAL,
	STJ.TJ_ORDEM as TJ_ORDEM,
	cast(ST9.T9_CODBEM as int) as T9_CODBEM,
	TR8.TR8_LOTE as TR8_LOTE,
	STJ.TJ_CCUSTO as CCUSTO,
	STJ.TJ_YITMCT as ATIVIDADE,

	STJ.TJ_CUSTTER,
	TQS.TQS_KMR1,
	TQS.TQS_KMR2,
	TQS.TQS_KMR3,
	TQS.TQS_KMR4,
	TQS.TQS_KMR5,
	TQS.TQS_KMR6,
	TQS.TQS_KMR7,
	TQS.TQS_KMOR,
	ST9.T9_VALCPA,
	TQS.TQS_KMOR + TQS.TQS_KMR1 + TQS.TQS_KMR2 + TQS.TQS_KMR3 + TQS.TQS_KMR4 + TQS.TQS_KMR5 + TQS.TQS_KMR6 + TQS.TQS_KMR7 as kmTOT,

	(
        select top 1 first_value(STZ010.TZ_DATAMOV) over (partition by STZ010.TZ_CODBEM order by STZ010.TZ_CODBEM)
        from STZ010 (nolock)
        where
                STZ010.D_E_L_E_T_ = ''
            and STZ010.TZ_CODBEM = ST9.T9_CODBEM
    ) as DATA,

	TR4.TR4_NUMANA,
	TR4.TR4_ORDEM,
	TR4.TR4_DESTIN,
	TR4.TR4_MOTIVO,
	convert(datetime, concat(TR4.TR4_DTANAL, ' ', TR4.TR4_HRANAL), 103) as DATA_ANALISE

from STJ010 STJ
	left join TR8010 TR8
		on TR8.D_E_L_E_T_ = ''
		and TR8.TR8_FILIAL = STJ.TJ_FILIAL
		and TR8.TR8_ORDEM = STJ.TJ_ORDEM
		and TR8.TR8_PLANO = STJ.TJ_PLANO

		left join TR4010 TR4
			on TR4.D_E_L_E_T_ = ''
			and TR4.TR4_CODBEM = TR8.TR8_CODBEM
			and TR4.TR4_ORDEM = TR8.TR8_ORDEM
			
	inner join TQS010 TQS
		on TQS.D_E_L_E_T_ = ''
		and TQS.TQS_CODBEM = STJ.TJ_CODBEM

		inner join ST9010 as ST9
			on ST9.D_E_L_E_T_ = ''
			and ST9.T9_CODBEM = TQS.TQS_CODBEM

where
		STJ.D_E_L_E_T_ = ''
