select
	ST9.T9_FILIAL as FILIAL,
	trim(ST9.T9_CODBEM) as T9_CODBEM,
	trim(ST9.T9_STATUS) as STATUS,
	trim(TQS.TQS_MEDIDA) as TQS_MEDIDA,
	ST9.T9_TIPMOD as MODELO,
	
    trim(ST9.T9_ITEMCTA) as T9_ITEMCTA,
    trim(ST9.T9_CCUSTO) as T9_CCUSTO,

	ST9.T9_VALCPA as CUSTO_COMPRA,
	ST9.T9_CONTACU as CONT_ACUMULADO,
	
	TQS.TQS_KMOR + TQS.TQS_KMR1 + TQS.TQS_KMR2 + TQS.TQS_KMR3 + TQS.TQS_KMR4 + TQS.TQS_KMR5 + TQS.TQS_KMR6 + TQS.TQS_KMR7 as TOTAL_VIDAS

from TQS010 TQS (nolock)
	inner join ST9010 ST9 (nolock)
		on ST9.D_E_L_E_T_ = ''
		and ST9.T9_CODBEM = TQS.TQS_CODBEM
where
		TQS.D_E_L_E_T_ = ''
